-- Secure admin foundation
alter table public.profiles add column if not exists role text not null default 'user';
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('user','admin','support'));
create index if not exists profiles_role_idx on public.profiles(role);
create table if not exists public.admin_logs (id uuid primary key default gen_random_uuid(),admin_id uuid not null references auth.users(id) on delete cascade,action text not null,target_user_id uuid references auth.users(id) on delete set null,target_message_id uuid references public.messages(id) on delete set null,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists admin_logs_created_at_idx on public.admin_logs(created_at desc);
alter table public.admin_logs enable row level security;
revoke all on public.admin_logs from anon;
revoke all on public.admin_logs from authenticated;
grant select,insert on public.admin_logs to authenticated;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin'); $$;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;
drop policy if exists "admins can read admin logs" on public.admin_logs;
drop policy if exists "admins can write admin logs" on public.admin_logs;
drop policy if exists "admins can manage profiles" on public.profiles;
drop policy if exists "admins can manage messages" on public.messages;
create policy "admins can read admin logs" on public.admin_logs for select to authenticated using (public.is_admin());
create policy "admins can write admin logs" on public.admin_logs for insert to authenticated with check (public.is_admin() and admin_id=auth.uid());
update public.profiles set role='admin' where lower(username)='parham';
create policy "admins can manage profiles" on public.profiles for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins can manage messages" on public.messages for all to authenticated using (public.is_admin()) with check (public.is_admin());
