"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const db=createClient("https://jcblfgrcsgbdeamogzfc.supabase.co","sb_publishable_9qBGewmR-UHx6Pc3_Gl36Q_7WhHCw2K");
const badge={none:"بدون تیک",blue:"🔵 تیک آبی",green:"🟢 تیک سبز",orange:"🟠 تیک نارنجی",red:"🔴 تیک قرمز"};
export default function AdminConversations(){const[rows,setRows]=useState([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(null),[err,setErr]=useState("");
 const load=async()=>{setLoading(true);setErr("");const{data,error}=await db.from("conversations").select("id,type,title,is_channel,channel_username,is_public,verification,created_at").order("created_at",{ascending:false}).limit(500);if(error)setErr(error.message);setRows(data||[]);setLoading(false)};
 useEffect(()=>{load()},[]); const visible=rows.filter(x=>`${x.title||""} ${x.channel_username||""}`.toLowerCase().includes(q.toLowerCase()));
 const save=async(id,verification)=>{setSaving(id);const{error}=await db.rpc("set_conversation_verification",{conversation_uuid:id,badge:verification});if(error)setErr(error.message);else setRows(r=>r.map(x=>x.id===id?{...x,verification}:x));setSaving(null)};
 return <section className="admin-card" dir="rtl"><div className="admin-toolbar"><div><strong>گروه‌ها و کانال‌ها</strong><small style={{display:"block",opacity:.65}}>تیک رسمی و وضعیت عمومی را مدیریت کن</small></div><button type="button" onClick={load}>بروزرسانی</button></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="جستجوی نام یا @شناسه" style={{width:"100%",margin:"10px 0",padding:12}}/>{err&&<div className="admin-error">{err}</div>}{loading?<p>در حال بارگذاری…</p>:<div className="admin-table-wrap"><table><thead><tr><th>عنوان</th><th>نوع</th><th>شناسه</th><th>تیک</th></tr></thead><tbody>{visible.map(x=><tr key={x.id}><td><b>{x.title||"بدون عنوان"}</b></td><td>{x.is_channel?"📢 کانال":"👥 گروه"}</td><td dir="ltr">{x.channel_username?`@${x.channel_username}`:"خصوصی"}</td><td><select disabled={saving===x.id} value={x.verification||"none"} onChange={e=>save(x.id,e.target.value)}>{Object.entries(badge).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></td></tr>)}</tbody></table></div>}</section>}
