"use client";
import {useCallback,useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const db=createClient("https://jcblfgrcsgbdeamogzfc.supabase.co","sb_publishable_9qBGewmR-UHx6Pc3_Gl36Q_7WhHCw2K");
const badges=[["none","بدون تیک"],["blue","🔵 تیک آبی"],["green","🟢 تیک سبز"],["orange","🟠 تیک نارنجی"],["red","🔴 تیک قرمز"]];
export default function GroupChannelManager(){
 const[g,setG]=useState([]),[c,setC]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[err,setErr]=useState(""),[msg,setMsg]=useState(""),[gf,setGf]=useState(""),[cf,setCf]=useState({title:"",username:"",description:"",public:true}),[edit,setEdit]=useState(null);
 const load=useCallback(async()=>{setLoading(true);const[{data:g1,error:e1},{data:c1,error:e2}]=await Promise.all([db.from("conversations").select("id,title,description,is_public,invite_token,badge,created_at").eq("type","group").eq("is_channel",false).order("created_at",{ascending:false}),db.from("channels").select("id,title,username,description,is_public,invite_token,badge,created_at").order("created_at",{ascending:false})]);if(e1||e2)setErr(e1?.message||e2?.message);setG(g1||[]);setC(c1||[]);setLoading(false)},[]);
 useEffect(()=>{load()},[load]);
 const createGroup=async e=>{e.preventDefault();if(!gf.trim())return;setBusy(true);const{error}=await db.rpc("create_group_conversation",{group_title:gf.trim(),member_ids:[]});if(error)setErr(error.message);else{setMsg("گروه خصوصی ساخته شد.");setGf("");await load()}setBusy(false)};
 const createChannel=async e=>{e.preventDefault();if(!cf.title.trim())return;setBusy(true);const{error}=await db.rpc("create_channel_conversation",{channel_title:cf.title.trim(),channel_description:cf.description.trim(),channel_username:cf.username.trim()||null,channel_public:cf.public});if(error)setErr(error.message);else{setMsg("کانال ساخته شد.");setCf({title:"",username:"",description:"",public:true});await load()}setBusy(false)};
 const save=async()=>{if(!edit?.title?.trim())return;setBusy(true);const fn=edit.type==="channel"?"admin_update_channel":"admin_update_conversation";const args=edit.type==="channel"?{channel_uuid:edit.id,new_title:edit.title,new_description:edit.description,new_public:edit.public,new_username:edit.username||null}:{conversation_uuid:edit.id,new_title:edit.title,new_description:edit.description,new_public:edit.public};const{error}=await db.rpc(fn,args);if(error)setErr(error.message);else{setMsg("تغییرات ذخیره شد.");setEdit(null);await load()}setBusy(false)};
 const badge=async(type,id,v)=>{setBusy(true);const{error}=await db.rpc(type==="channel"?"admin_set_channel_badge":"admin_set_conversation_badge",type==="channel"?{channel_uuid:id,badge_value:v}:{conversation_uuid:id,badge_value:v});if(error)setErr(error.message);else{setMsg("تیک ذخیره شد.");await load()}setBusy(false)};
 const regenerate=async(type,id)=>{setBusy(true);const{data,error}=await db.rpc(type==="channel"?"admin_regenerate_channel_invite":"admin_regenerate_invite",type==="channel"?{channel_uuid:id}:{conversation_uuid:id});if(error)setErr(error.message);else{await navigator.clipboard?.writeText(`${location.origin}/messenger/?invite=${encodeURIComponent(data)}`);setMsg("لینک دعوت جدید ساخته و کپی شد.");await load()}setBusy(false)};
 const del=async(type,id,title)=>{if(!confirm(`«${title}» حذف شود؟`))return;setBusy(true);const{error}=await db.rpc(type==="channel"?"admin_delete_channel":"admin_delete_conversation",type==="channel"?{channel_uuid:id}:{conversation_uuid:id});if(error)setErr(error.message);else{setMsg("حذف شد.");await load()}setBusy(false)};
 const copy=x=>navigator.clipboard?.writeText(`${location.origin}/messenger/?invite=${encodeURIComponent(x.invite_token)}`);
 if(loading)return <div className="admin-card">در حال بارگذاری…</div>;
 return <div className="admin-stack">{err&&<div className="admin-error">{err}<button onClick={()=>setErr("")}>×</button></div>}{msg&&<div className="admin-success">{msg}<button onClick={()=>setMsg("")}>×</button></div>}
 <div className="admin-grid"><div className="admin-card form-card"><h2>👥 ساخت گروه خصوصی</h2><form onSubmit={createGroup}><label>نام گروه<input required maxLength={80} value={gf} onChange={e=>setGf(e.target.value)}/></label><p className="muted">عمومی نیست. ورود فقط با لینک دعوت یا مدیریت اعضا انجام می‌شود.</p><button className="admin-button primary" disabled={busy}>ساخت گروه</button></form></div>
 <div className="admin-card form-card"><h2>📢 ساخت کانال</h2><form onSubmit={createChannel}><label>نام<input required maxLength={80} value={cf.title} onChange={e=>setCf({...cf,title:e.target.value})}/></label><label>شناسه عمومی<input dir="ltr" maxLength={32} pattern="[a-z0-9_]{3,32}" placeholder="mychannel" value={cf.username} onChange={e=>setCf({...cf,username:e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,"")})}/></label><label>توضیحات<textarea maxLength={500} value={cf.description} onChange={e=>setCf({...cf,description:e.target.value})}/></label><label><input type="checkbox" checked={cf.public} onChange={e=>setCf({...cf,public:e.target.checked})}/> عمومی و قابل جستجو</label><button className="admin-button primary" disabled={busy}>ساخت کانال</button></form></div></div>
 <div className="admin-card"><div className="admin-toolbar"><h2>گروه‌ها ({g.length})</h2></div><div className="admin-table-wrap"><table><thead><tr><th>نام</th><th>تیک</th><th>لینک</th><th>عملیات</th></tr></thead><tbody>{g.map(x=><tr key={x.id}><td>👥 <b>{x.title}</b></td><td><select value={x.badge||"none"} disabled={busy} onChange={e=>badge("group",x.id,e.target.value)}>{badges.map(b=><option value={b[0]} key={b[0]}>{b[1]}</option>)}</select></td><td>{x.invite_token&&<button onClick={()=>copy(x)}>کپی</button>}<button onClick={()=>regenerate("group",x.id)}>لینک جدید</button></td><td><div className="row-actions"><button onClick={()=>setEdit({type:"group",id:x.id,title:x.title,description:x.description||"",public:!!x.is_public})}>ویرایش</button><button className="danger" disabled={busy} onClick={()=>del("group",x.id,x.title)}>حذف</button></div></td></tr>)}</tbody></table></div></div>
 <div className="admin-card"><h2>کانال‌ها ({c.length})</h2><div className="admin-table-wrap"><table><thead><tr><th>نام</th><th>شناسه</th><th>حالت</th><th>تیک</th><th>عملیات</th></tr></thead><tbody>{c.map(x=><tr key={x.id}><td>📢 <b>{x.title}</b></td><td dir="ltr">{x.username?`@${x.username}`:"خصوصی"}</td><td>{x.is_public?"عمومی":"خصوصی"}</td><td><select value={x.badge||"none"} disabled={busy} onChange={e=>badge("channel",x.id,e.target.value)}>{badges.map(b=><option value={b[0]} key={b[0]}>{b[1]}</option>)}</select></td><td><div className="row-actions">{x.invite_token&&<button onClick={()=>copy(x)}>کپی لینک</button>}<button onClick={()=>regenerate("channel",x.id)}>لینک جدید</button><button onClick={()=>setEdit({type:"channel",id:x.id,title:x.title,username:x.username||"",description:x.description||"",public:!!x.is_public})}>ویرایش</button><button className="danger" disabled={busy} onClick={()=>del("channel",x.id,x.title)}>حذف</button></div></td></tr>)}</tbody></table></div></div>
 {edit&&<div className="admin-modal-backdrop"><div className="admin-card admin-modal"><h2>ویرایش {edit.type==="channel"?"کانال":"گروه"}</h2><label>نام<input value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></label>{edit.type==="channel"&&<label>شناسه<input dir="ltr" value={edit.username} onChange={e=>setEdit({...edit,username:e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,"")})}/></label>}<label>توضیحات<textarea value={edit.description} onChange={e=>setEdit({...edit,description:e.target.value})}/></label>{edit.type==="channel"&&<label><input type="checkbox" checked={edit.public} onChange={e=>setEdit({...edit,public:e.target.checked})}/> عمومی</label>}<div className="form-actions"><button className="admin-button primary" disabled={busy} onClick={save}>ذخیره</button><button className="admin-button" onClick={()=>setEdit(null)}>لغو</button></div></div></div>}</div>;
}
