"use client";
import{useCallback,useEffect,useMemo,useState}from"react";
import{createClient}from"@supabase/supabase-js";
import mapError from"../lib/error-map";
const db=createClient("https://jcblfgrcsgbdeamogzfc.supabase.co","sb_publishable_9qBGewmR-UHx6Pc3_Gl36Q_7WhHCw2K",{auth:{persistSession:true,autoRefreshToken:true}});
const badges=[["none","بدون تیک"],["blue","تیک آبی"],["green","تیک سبز"],["orange","تیک نارنجی"],["red","تیک قرمز"]];
export default function GroupChannelManager(){const[groups,setGroups]=useState([]),[channels,setChannels]=useState([]),[users,setUsers]=useState([]),[members,setMembers]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[err,setErr]=useState(""),[ok,setOk]=useState(""),[groupName,setGroupName]=useState(""),[groupDescription,setGroupDescription]=useState(""),[groupPublic,setGroupPublic]=useState(false),[channelForm,setChannelForm]=useState({title:"",username:"",description:"",public:false}),[edit,setEdit]=useState(null),[userQ,setUserQ]=useState("");
 const load=useCallback(async()=>{setLoading(true);setErr("");const[{data:g,error:ge},{data:c,error:ce},{data:u,error:ue}]=await Promise.all([db.from("conversations").select("id,title,description,is_public,invite_token,badge,created_at").eq("type","group").eq("is_channel",false).order("created_at",{ascending:false}),db.from("channels").select("id,title,username,description,is_public,invite_token,badge,created_at").order("created_at",{ascending:false}),db.rpc("admin_list_profiles")]);if(ge||ce||ue)setErr(mapError(ge||ce||ue));setGroups(g||[]);setChannels(c||[]);setUsers(u||[]);setLoading(false)},[]);
 useEffect(()=>{load()},[load]);
 const loadMembers=useCallback(async item=>{if(!item){setMembers([]);return}setBusy(true);const{data,error}=await db.rpc("admin_get_conversation_members",{conversation_uuid:item.id});setBusy(false);if(error)setErr(mapError(error));else setMembers(data||[])},[]);
 useEffect(()=>{loadMembers(selected)},[selected,loadMembers]);
 const filteredUsers=useMemo(()=>{const q=userQ.trim().toLowerCase();return users.filter(u=>!q||`${u.username} ${u.display_name} ${u.id}`.toLowerCase().includes(q)).slice(0,30)},[users,userQ]);
 async function run(fn,args,success){setBusy(true);setErr("");const{error}=await db.rpc(fn,args);setBusy(false);if(error){setErr(mapError(error));return false}setOk(success);await load();if(selected)await loadMembers(selected);return true}
 async function createGroup(e){e.preventDefault();const title=groupName.trim(),description=groupDescription.trim();if(!title)return;if(title.length>128||description.length>1000)return setErr(title.length>128?mapError("invalid_title"):mapError("invalid_description"));const good=await run("create_conversation",{p_kind:"group",p_title:title,p_description:description,p_is_public:groupPublic,p_username:null,p_member_ids:[]},groupPublic?"گروه عمومی ساخته شد.":"گروه خصوصی ساخته شد.");if(good){setGroupName("");setGroupDescription("");setGroupPublic(false)}}
 async function createChannel(e){e.preventDefault();const title=channelForm.title.trim(),username=channelForm.username.trim().toLowerCase(),description=channelForm.description.trim();if(!title)return;if(title.length>128||description.length>1000)return setErr(title.length>128?mapError("invalid_title"):mapError("invalid_description"));if(channelForm.public&&!username){setErr(mapError("username_required_for_public_channel"));return}if(!channelForm.public&&username){setErr(mapError("private_channel_username_not_allowed"));return}if(username&&!/^[a-z0-9_]{3,20}$/.test(username)){setErr(mapError("invalid_channel_username"));return}const good=await run("create_conversation",{p_kind:"channel",p_title:title,p_description:description,p_is_public:channelForm.public,p_username:username||null,p_member_ids:[]},channelForm.public?"کانال عمومی ساخته شد.":"کانال خصوصی ساخته شد.");if(good)setChannelForm({title:"",username:"",description:"",public:false})}
 async function save(){if(!edit?.title?.trim())return;const fn=edit.type==="channel"?"admin_update_channel":"admin_update_conversation";if(edit.type==="channel"&&edit.public&&!/^[a-z0-9_]{3,20}$/.test(edit.username||""))return setErr(mapError(edit.username?"invalid_channel_username":"username_required_for_public_channel"));if(edit.type==="channel"&&!edit.public&&edit.username)return setErr(mapError("private_channel_username_not_allowed"));const args=edit.type==="channel"?{channel_uuid:edit.id,new_title:edit.title.trim(),new_description:edit.description.trim(),new_public:edit.public,new_username:edit.username||null}:{conversation_uuid:edit.id,new_title:edit.title.trim(),new_description:edit.description.trim(),new_public:!!edit.public};if(await run(fn,args,"تغییرات ذخیره شد."))setEdit(null)}
 async function setBadge(item,value){await run(item.type==="channel"?"admin_set_channel_badge":"admin_set_conversation_badge",item.type==="channel"?{channel_uuid:item.id,badge_value:value}:{conversation_uuid:item.id,badge_value:value},"تیک ذخیره شد.")}
 async function regenerate(item){setBusy(true);const{data,error}=await db.rpc(item.type==="channel"?"admin_regenerate_channel_invite":"admin_regenerate_invite",item.type==="channel"?{channel_uuid:item.id}:{conversation_uuid:item.id});setBusy(false);if(error){setErr(mapError(error));return}const link=`${location.origin}/messenger/?invite=${encodeURIComponent(data)}`;try{await navigator.clipboard.writeText(link)}catch{}setOk("لینک دعوت جدید ساخته شد و در صورت امکان کپی شد.");await load()}
 async function removeItem(item){if(!confirm(`«${item.title}» حذف شود؟ این عملیات قابل بازگشت نیست.`))return;await run(item.type==="channel"?"admin_delete_channel":"admin_delete_conversation",item.type==="channel"?{channel_uuid:item.id}:{conversation_uuid:item.id},"حذف شد.");if(selected?.id===item.id)setSelected(null)}
 async function addMember(uid){if(!selected)return;await run("admin_add_conversation_member",{conversation_uuid:selected.id,user_uuid:uid},"کاربر به گروه/کانال اضافه شد.");setUserQ("")}
 async function removeMember(uid){if(!selected||!confirm("این عضو از گروه/کانال حذف شود؟"))return;await run("admin_remove_conversation_member",{conversation_uuid:selected.id,user_uuid:uid},"عضو حذف شد.")}
 const copy=item=>{const token=item.invite_token;if(!token){setErr("برای این مورد لینک دعوت وجود ندارد.");return}const link=`${location.origin}/messenger/?invite=${encodeURIComponent(token)}`;navigator.clipboard?.writeText(link);setOk("لینک دعوت کپی شد.")};
 if(loading)return <div className="admin-card">در حال بارگذاری مدیریت گروه و کانال…</div>;
 return <div className="admin-stack">{err&&<div className="admin-error">{err}<button type="button" onClick={()=>setErr("")}>×</button></div>}{ok&&<div className="admin-success">{ok}<button type="button" onClick={()=>setOk("")}>×</button></div>}
  <div className="admin-grid">
   <div className="admin-card form-card"><h2>ساخت گروه</h2><p className="muted">گروه را عمومی و قابل جستجو یا خصوصی و فقط با دعوت بساز.</p><form onSubmit={createGroup}><label>نام گروه<input required maxLength={128} value={groupName} onChange={e=>setGroupName(e.target.value)}/></label><label>توضیحات<textarea maxLength={1000} value={groupDescription} onChange={e=>setGroupDescription(e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={groupPublic} onChange={e=>setGroupPublic(e.target.checked)}/> عمومی و قابل جستجو</label><button className="admin-button primary" disabled={busy||!groupName.trim()}>ساخت گروه</button></form></div>
   <div className="admin-card form-card"><h2>ساخت کانال</h2><p className="muted">کانال می‌تواند خصوصی یا عمومی و قابل جستجو باشد.</p><form onSubmit={createChannel}><label>نام<input required maxLength={128} value={channelForm.title} onChange={e=>setChannelForm({...channelForm,title:e.target.value})}/></label><label>شناسه عمومی<input disabled={!channelForm.public} dir="ltr" maxLength={20} pattern="[a-z0-9_]{3,20}" placeholder={channelForm.public?"mychannel":"برای کانال خصوصی لازم نیست"} value={channelForm.username} onChange={e=>setChannelForm({...channelForm,username:e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,"")})}/></label><label>توضیحات<textarea maxLength={1000} value={channelForm.description} onChange={e=>setChannelForm({...channelForm,description:e.target.value})}/></label><label className="check-row"><input type="checkbox" checked={channelForm.public} onChange={e=>setChannelForm({...channelForm,public:e.target.checked})}/> عمومی و قابل جستجو</label><button className="admin-button primary" disabled={busy||!channelForm.title.trim()||(channelForm.public&&!channelForm.username.trim())}>ساخت کانال</button></form></div>
  </div>
  <div className="admin-card"><div className="admin-toolbar"><h2>گروه‌ها <span className="admin-count">{groups.length}</span></h2></div><div className="admin-table-wrap"><table><thead><tr><th>گروه</th><th>وضعیت</th><th>تیک</th><th>دعوت</th><th>عملیات</th></tr></thead><tbody>{groups.map(x=>{const item={...x,type:"group"};return <tr key={x.id}><td><button className="table-link" onClick={()=>setSelected(item)}>{x.title}</button></td><td>{x.is_public?"عمومی":"خصوصی"}</td><td><select disabled={busy} value={x.badge||"none"} onChange={e=>setBadge(item,e.target.value)}>{badges.map(b=><option value={b[0]} key={b[0]}>{b[1]}</option>)}</select></td><td><button disabled={x.is_public} onClick={()=>copy(x)}>کپی لینک</button>{!x.is_public&&<button onClick={()=>regenerate(item)}>لینک جدید</button>}</td><td><div className="row-actions"><button onClick={()=>setSelected(item)}>اعضا</button><button onClick={()=>setEdit({type:"group",id:x.id,title:x.title,description:x.description||"",public:!!x.is_public})}>ویرایش</button><button className="danger" disabled={busy} onClick={()=>removeItem(item)}>حذف</button></div></td></tr>})}</tbody></table></div></div>
  <div className="admin-card"><div className="admin-toolbar"><h2>کانال‌ها <span className="admin-count">{channels.length}</span></h2></div><div className="admin-table-wrap"><table><thead><tr><th>کانال</th><th>شناسه</th><th>وضعیت</th><th>تیک</th><th>عملیات</th></tr></thead><tbody>{channels.map(x=>{const item={...x,type:"channel"};return <tr key={x.id}><td><button className="table-link" onClick={()=>setSelected(item)}>{x.title}</button></td><td dir="ltr">{x.username?`@${x.username}`:"خصوصی"}</td><td>{x.is_public?"عمومی":"خصوصی"}</td><td><select disabled={busy} value={x.badge||"none"} onChange={e=>setBadge(item,e.target.value)}>{badges.map(b=><option value={b[0]} key={b[0]}>{b[1]}</option>)}</select></td><td><div className="row-actions"><button onClick={()=>setSelected(item)}>اعضا</button><button onClick={()=>copy(x)}>کپی لینک</button><button onClick={()=>regenerate(item)}>لینک جدید</button><button onClick={()=>setEdit({type:"channel",id:x.id,title:x.title,username:x.username||"",description:x.description||"",public:!!x.is_public})}>ویرایش</button><button className="danger" disabled={busy} onClick={()=>removeItem(item)}>حذف</button></div></td></tr>})}</tbody></table></div></div>
  {selected&&<div className="admin-card member-manager"><div className="admin-toolbar"><div><h2>مدیریت اعضا: {selected.title}</h2><p className="muted">اضافه یا حذف عضو با دسترسی مدیریتی کامل.</p></div><button onClick={()=>setSelected(null)}>بستن</button></div><div className="member-add"><input dir="ltr" placeholder="جستجوی @username یا نام" value={userQ} onChange={e=>setUserQ(e.target.value)}/><div className="member-suggestions">{filteredUsers.filter(u=>!members.some(m=>m.user_id===u.id)).slice(0,10).map(u=><button key={u.id} disabled={busy} onClick={()=>addMember(u.id)}><b>@{u.username}</b><span>{u.display_name}</span></button>)}</div></div><div className="admin-table-wrap"><table><thead><tr><th>کاربر</th><th>نقش</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{members.map(m=><tr key={m.user_id}><td dir="ltr">@{m.username}</td><td>{m.role}</td><td>{m.is_banned?"مسدود":"فعال"}</td><td>{m.role!=="owner"&&<button className="danger" disabled={busy} onClick={()=>removeMember(m.user_id)}>حذف عضو</button>}</td></tr>)}</tbody></table></div></div>}
  {edit&&<div className="admin-modal-backdrop"><div className="admin-card admin-modal"><h2>ویرایش {edit.type==="channel"?"کانال":"گروه"}</h2><label>نام<input required maxLength={128} value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></label>{edit.type==="channel"&&<label>شناسه<input disabled={!edit.public} dir="ltr" maxLength={20} pattern="[a-z0-9_]{3,20}" value={edit.username} onChange={e=>setEdit({...edit,username:e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,"")})}/></label>}<label>توضیحات<textarea maxLength={1000} value={edit.description} onChange={e=>setEdit({...edit,description:e.target.value})}/></label><label className="check-row"><input type="checkbox" checked={!!edit.public} onChange={e=>setEdit({...edit,public:e.target.checked,username:e.target.checked?edit.username:"")}/> عمومی و قابل جستجو</label><div className="form-actions"><button className="admin-button primary" disabled={busy} onClick={save}>ذخیره</button><button className="admin-button" onClick={()=>setEdit(null)}>لغو</button></div></div></div>}
 </div>;
}
