"use client";
import{useCallback,useEffect,useMemo,useState}from"react";
import{createClient}from"@supabase/supabase-js";
import mapError from"../lib/error-map";
import "../utino-platform.css";
import "./admin.css";
import "./admin-polish.css";
import GroupChannelManager from "./GroupChannelManager";
const SUPABASE_URL="https://jcblfgrcsgbdeamogzfc.supabase.co";
const KEY="sb_publishable_9qBGewmR-UHx6Pc3_Gl36Q_7WhHCw2K";
const db=createClient(SUPABASE_URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const tabs=[["home","داشبورد"],["users","کاربران"],["create","ساخت کاربر"],["groups","گروه و کانال"],["messages","همه پیام‌ها"],["tickets","تیکت‌ها"],["logs","لاگ‌ها"],["settings","تنظیمات"]];
const badges=[["none","بدون تیک"],["blue","تیک آبی"],["green","تیک سبز"],["orange","تیک نارنجی"],["red","تیک قرمز"]];
const roles=[["user","کاربر"],["support","پشتیبانی"],["admin","ادمین"]];
const banDurations=[["1h","۱ ساعت"],["24h","۲۴ ساعت"],["7d","۷ روز"],["30d","۳۰ روز"],["permanent","دائمی"]];
export default function Admin(){const[me,setMe]=useState(null),[users,setUsers]=useState([]),[msgs,setMsgs]=useState([]),[tickets,setTickets]=useState([]),[logs,setLogs]=useState([]),[tab,setTab]=useState("home"),[q,setQ]=useState(""),[err,setErr]=useState(""),[ok,setOk]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[reg,setReg]=useState(false),[form,setForm]=useState({username:"",display_name:"",password:"",role:"user",verification:"none"}),[edit,setEdit]=useState(null);
const fail=e=>setErr(mapError(e,"fa"));
const load=useCallback(async()=>{setLoading(true);try{const{data:{user}}=await db.auth.getUser();if(!user){location.href="/";return}const{data:p,error:pe}=await db.from("profiles").select("id,username,display_name,role,public_id,is_verified,is_banned,verification,created_at").eq("id",user.id).single();if(pe||p?.role!=="admin"){setErr("دسترسی غیرمجاز");setLoading(false);return}setMe(p);const[u,m,t,l,s]=await Promise.all([db.from("profiles").select("id,username,display_name,role,public_id,is_verified,is_banned,verification,created_at").order("created_at",{ascending:false}),db.from("messages").select("id,sender_id,receiver_id,conversation_id,content,message_type,file_name,created_at,edited_at,deleted_at").order("created_at",{ascending:false}).limit(1000),db.from("support_tickets").select("id,user_id,subject,status,priority,created_at,updated_at").order("updated_at",{ascending:false}).limit(500),db.from("admin_logs").select("id,action,target_user_id,target_message_id,details,created_at").order("created_at",{ascending:false}).limit(500),db.from("app_settings").select("value").eq("key","registration_enabled").maybeSingle()]);if(u.error||m.error||t.error||l.error||s.error)throw(u.error||m.error||t.error||l.error||s.error);setUsers(u.data||[]);setMsgs(m.data||[]);setTickets(t.data||[]);setLogs(l.data||[]);setReg(s.data?.value===true)}catch(e){fail(e)}finally{setLoading(false)}},[]);
useEffect(()=>{load()},[load]);
async function action(payload){if(busy)return false;setBusy(true);setErr("");try{if(payload.action==="set_registration"){const{error}=await db.rpc("set_registration_enabled",{enabled:payload.enabled});if(error)throw error;await load();return true}const{data:{session}}=await db.auth.getSession();if(!session){fail("unauthorized");return false}const{data:j,error:invokeError}=await db.functions.invoke("admin-user-actions",{body:payload,headers:{Authorization:`Bearer ${session.access_token}`}});if(invokeError){fail(invokeError);return false}if(!j?.ok){fail(j?.error||"server_error");return false}await load();return true}catch(e){fail(e);return false}finally{setBusy(false)}}
async function createUser(e){e.preventDefault();if(!/^[a-z0-9_]{3,20}$/.test(form.username.trim().toLowerCase()))return fail("invalid_username");if(form.password.length<6||form.password.length>128)return fail("weak_password");if(!form.display_name.trim())return fail("invalid_display_name");const good=await action({action:"create_user",username:form.username.trim().toLowerCase(),display_name:form.display_name,password:form.password,role:form.role,verification:form.verification});if(good){setForm({username:"",display_name:"",password:"",role:"user",verification:"none"});setOk("کاربر ساخته شد.");setTab("users")}}
async function verify(x,v){if(await action({action:"set_verification",user_id:x.id,verification:v}))setOk("نشان ذخیره شد.")}
async function setRole(x,role){if(await action({action:"set_role",user_id:x.id,role}))setOk("نقش کاربر تغییر کرد.")}
async function userOp(x,a){if(a==="delete_user"&&!confirm(`@${x.username} حذف شود؟`))return;if(a==="ban"){if(!confirm(`@${x.username} مسدود شود؟`))return;const duration=prompt("مدت مسدودی را وارد کنید: 1h، 24h، 7d، 30d یا permanent","24h");if(!duration||!banDurations.some(d=>d[0]===duration))return setErr("مدت مسدودی معتبر نیست.");return action({action:"ban",user_id:x.id,duration})}if(a==="reset_password"){const p=prompt("رمز جدید، ۶ تا ۱۲۸ کاراکتر:");if(!p||p.length<6||p.length>128)return;return action({action:a,user_id:x.id,password:p})}return action({action:a,user_id:x.id})}
async function editMsg(){if(!edit?.content?.trim())return fail("invalid_message");setBusy(true);const{error}=await db.rpc("edit_message",{message_uuid:edit.id,new_content:edit.content.trim()});setBusy(false);if(error)return fail(error);setEdit(null);setOk("پیام ویرایش شد.");await load()}
async function delMsg(x){if(!confirm("پیام حذف شود؟"))return;setBusy(true);const{error}=await db.rpc("delete_message",{message_uuid:x.id});setBusy(false);if(error)return fail(error);setOk("پیام حذف شد.");await load()}
async function regToggle(){if(await action({action:"set_registration",enabled:!reg})){setReg(!reg);setOk(!reg?"ثبت‌نام عمومی روشن شد.":"ثبت‌نام عمومی خاموش شد.")}}
const filtered=useMemo(()=>{const s=q.trim().toLowerCase();return s?msgs.filter(x=>`${x.content||""} ${x.sender_id||""} ${x.receiver_id||""}`.toLowerCase().includes(s)):msgs},[msgs,q]);
if(loading)return <main className="admin-shell platform-page"><div className="admin-loading">در حال بارگذاری UTINOCHATV1…</div></main>;if(!me)return <main className="admin-shell platform-page"><div className="admin-card"><h1>403</h1><p>{err}</p><a href="/">بازگشت</a></div></main>;
return <main className="admin-shell platform-page" dir="rtl"><aside className="admin-sidebar"><div className="admin-brand"><strong>UTINOCHATV1</strong><small>@{me.username} · Admin</small></div>{tabs.filter(([k])=>k!=="settings"||me.username?.toLowerCase()==="parham").map(([k,v])=><button type="button" className={tab===k?"active":""} onClick={()=>{setTab(k);setErr("");setOk("")}} key={k}>{v}</button>)}<button type="button" onClick={()=>location.href="/messenger/"}>بازگشت به پیام‌رسان</button><button type="button" onClick={async()=>{await db.auth.signOut();location.href="/"}}>خروج</button></aside><section className="admin-main"><header className="admin-header"><div><h1>{tabs.find(x=>x[0]===tab)?.[1]}</h1><span>کنترل مرکزی UTINOCHATV1</span></div><button type="button" onClick={load} disabled={busy}>↻</button></header>{err&&<div className="admin-error" role="alert">{err}<button onClick={()=>setErr("")}>×</button></div>}{ok&&<div className="admin-success" role="status">{ok}<button onClick={()=>setOk("")}>×</button></div>}
{tab==="home"&&<div className="admin-grid"><div className="admin-stat"><b>{users.length}</b><span>کاربر</span></div><div className="admin-stat"><b>{users.filter(x=>x.role==="admin").length}</b><span>ادمین</span></div><div className="admin-stat"><b>{msgs.length}</b><span>پیام</span></div><div className="admin-stat"><b>{tickets.filter(x=>x.status!=="closed").length}</b><span>تیکت باز</span></div><div className="admin-card"><h2>وضعیت سیستم</h2><p>Auth و Database متصل هستند.</p><p>مدیریت کاربران، پیام‌ها، گروه‌ها، کانال‌ها و تیکت‌ها از همین پنل انجام می‌شود.</p></div></div>}
{tab==="users"&&<div className="admin-card"><div className="admin-toolbar"><strong>{users.length} کاربر</strong><button className="admin-button primary utino-primary" onClick={()=>setTab("create")}>+ ساخت کاربر</button></div><div className="admin-table-wrap"><table><thead><tr><th>کاربر</th><th>نام</th><th>نقش</th><th>تیک</th><th>عملیات</th></tr></thead><tbody>{users.map(x=><tr key={x.id}><td><b>@{x.username}</b><small>{x.public_id||""}</small></td><td>{x.display_name||"-"}</td><td><select disabled={busy||x.id===me.id} value={x.role||"user"} onChange={e=>setRole(x,e.target.value)}>{roles.map(r=><option value={r[0]} key={r[0]}>{r[1]}</option>)}</select></td><td><select disabled={busy} value={x.verification||"none"} onChange={e=>verify(x,e.target.value)}>{badges.map(b=><option value={b[0]} key={b[0]}>{b[1]}</option>)}</select></td><td><div className="row-actions"><button disabled={busy} onClick={()=>userOp(x,"reset_password")}>رمز</button><button disabled={busy||x.id===me.id} onClick={()=>userOp(x,x.is_banned?"unban":"ban")}>{x.is_banned?"رفع مسدودی":"مسدود"}</button>{x.id!==me.id&&<button className="danger" disabled={busy} onClick={()=>userOp(x,"delete_user")}>حذف</button>}</div></td></tr>)}</tbody></table></div></div>}
{tab==="create"&&<div className="admin-card form-card"><h2>ساخت کاربر جدید</h2><form onSubmit={createUser}><label>نام کاربری<input required minLength={3} maxLength={20} pattern="[a-z0-9_]+" value={form.username} onChange={e=>setForm({...form,username:e.target.value.replace(/[^a-z0-9_]/gi,"").toLowerCase()})}/></label><label>نام نمایشی<input required maxLength={80} value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/></label><label>رمز عبور<input required minLength={6} maxLength={128} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>نقش<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{roles.map(r=><option value={r[0]} key={r[0]}>{r[1]}</option>)}</select></label><label>نشان تأیید<select value={form.verification} onChange={e=>setForm({...form,verification:e.target.value})}>{badges.map(b=><option value={b[0]} key={b[0]}>{b[1]}</option>)}</select></label><button className="admin-button primary utino-primary" disabled={busy}>{busy?"در حال ساخت…":"ساخت کاربر"}</button></form></div>}
{tab==="groups"&&<GroupChannelManager/>}
{tab==="messages"&&<div className="admin-card"><div className="admin-toolbar"><strong>همه پیام‌ها ({filtered.length})</strong><input className="admin-search utino-field" placeholder="جستجوی پیام…" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="admin-table-wrap"><table><thead><tr><th>پیام</th><th>فرستنده</th><th>نوع</th><th>زمان</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td>{x.deleted_at?"این پیام حذف شده است.":(x.content||x.file_name||"")}</td><td dir="ltr">{x.sender_id?.slice(0,8)}</td><td>{x.message_type}</td><td>{new Date(x.created_at).toLocaleString("fa-IR")}</td><td>{x.deleted_at?"حذف‌شده":x.edited_at?"ویرایش‌شده":"عادی"}</td><td>{!x.deleted_at&&<div className="row-actions"><button disabled={busy} onClick={()=>setEdit({id:x.id,content:x.content||""})}>ویرایش</button><button className="danger" disabled={busy} onClick={()=>delMsg(x)}>حذف</button></div>}</td></tr>)}</tbody></table></div></div>}
{tab==="tickets"&&<div className="admin-card"><h2>تیکت‌ها</h2><div className="admin-table-wrap"><table><thead><tr><th>تیکت</th><th>کاربر</th><th>وضعیت</th><th>اولویت</th><th>زمان</th></tr></thead><tbody>{tickets.map(x=><tr key={x.id}><td>{x.subject||"بدون موضوع"}</td><td dir="ltr">{x.user_id?.slice(0,8)}</td><td>{x.status}</td><td>{x.priority}</td><td>{new Date(x.updated_at||x.created_at).toLocaleString("fa-IR")}</td></tr>)}</tbody></table></div></div>}
{tab==="logs"&&<div className="admin-card"><h2>لاگ‌های مدیریت</h2><div className="admin-table-wrap"><table><thead><tr><th>عملیات</th><th>جزئیات</th><th>زمان</th></tr></thead><tbody>{logs.map(x=><tr key={x.id}><td>{x.action}</td><td>{typeof x.details==="string"?x.details:JSON.stringify(x.details||{})}</td><td>{new Date(x.created_at).toLocaleString("fa-IR")}</td></tr>)}</tbody></table></div></div>}
{tab==="settings"&&<div className="admin-card"><h2>تنظیمات اصلی</h2><p>فقط مالک @parham این بخش را می‌بیند.</p><div className="registration-setting"><div><strong>ثبت‌نام عمومی</strong><span>{reg?"روشن":"خاموش"}</span></div><button className={`admin-button ${reg?"danger":"primary"}`} disabled={busy} onClick={regToggle}>{reg?"خاموش کردن":"روشن کردن"}</button></div></div>}
{edit&&<div className="admin-modal-backdrop"><div className="admin-card admin-modal"><h2>ویرایش پیام</h2><textarea autoFocus maxLength={4000} value={edit.content} onChange={e=>setEdit({...edit,content:e.target.value})}/><div className="form-actions"><button className="admin-button primary utino-primary" disabled={busy} onClick={editMsg}>ذخیره</button><button className="admin-button" onClick={()=>setEdit(null)}>لغو</button></div></div></div>}
</section></main>}
