"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";
import "./admin.css";
const db=createClient("https://jcblfgrcsgbdeamogzfc.supabase.co","sb_publishable_9qBGewmR-UHx6Pc3_Gl36Q_7WhHCw2K",{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const tabs=[["home","داشبورد"],["users","کاربران"],["create","ساخت کاربر"],["messages","پیام‌ها"],["logs","لاگ‌ها"],["tickets","پشتیبانی"],["settings","تنظیمات"]];
const friendly=e=>({invalid_username:"نام کاربری باید ۳ تا ۲۰ کاراکتر انگلیسی کوچک، عدد یا _ باشد.",username_exists:"این نام کاربری قبلاً استفاده شده است.",weak_password:"رمز عبور باید حداقل ۶ کاراکتر باشد.",invalid_display_name:"نام نمایشی باید وارد شود و حداکثر ۸۰ کاراکتر باشد.",auth_create_failed:"ساخت حساب در Auth انجام نشد.",profile_create_failed:"پروفایل کاربر ساخته نشد و عملیات برگشت داده شد.",profile_lookup_failed:"بررسی نام کاربری انجام نشد.",log_failed:"کاربر ساخته شد، اما ثبت لاگ مدیریت انجام نشد.",cannot_remove_own_admin:"نمی‌توانی دسترسی ادمین خودت را حذف کنی.",cannot_ban_self:"نمی‌توانی خودت را مسدود کنی.",cannot_delete_self:"نمی‌توانی خودت را حذف کنی.",forbidden:"دسترسی غیرمجاز",unauthorized:"نشست ورود معتبر نیست.",server_error:"ارتباط با سرور برقرار نشد. اینترنت یا Supabase را بررسی کن."}[e]||e||"خطای نامشخص");
const badgeLabel=v=>({blue:"تأیید آبی",green:"تأیید سبز",orange:"تأیید نارنجی",red:"تأیید قرمز",none:"عادی"}[v]||"عادی");
export default function Admin(){const[me,setMe]=useState(null),[users,setUsers]=useState([]),[msgs,setMsgs]=useState([]),[logs,setLogs]=useState([]),[tab,setTab]=useState("home"),[err,setErr]=useState(""),[success,setSuccess]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[form,setForm]=useState({username:"",display_name:"",password:"",role:"user",verification:"none"}),[registrationEnabled,setRegistrationEnabled]=useState(false);
async function load(){setLoading(true);setErr("");try{const{data:{user}}=await db.auth.getUser();if(!user){location.href="/";return}const{data:p,error:pe}=await db.from("profiles").select("id,username,display_name,role,public_id,is_verified,is_banned,verification,created_at").eq("id",user.id).single();if(pe||p?.role!=="admin"){setErr("دسترسی غیرمجاز");setLoading(false);return}setMe(p);const[u,m,l,s]=await Promise.all([db.from("profiles").select("id,username,display_name,role,public_id,is_verified,is_banned,verification,created_at").order("created_at",{ascending:false}),db.from("messages").select("id,sender_id,receiver_id,content,message_type,file_name,created_at").order("created_at",{ascending:false}).limit(200),db.from("admin_logs").select("id,action,target_user_id,target_message_id,details,created_at").order("created_at",{ascending:false}).limit(200),db.from("app_settings").select("value").eq("key","registration_enabled").maybeSingle()]);if(u.error||m.error||l.error)throw new Error(u.error?.message||m.error?.message||l.error?.message);setUsers(u.data||[]);setMsgs(m.data||[]);setLogs(l.data||[]);if(!s.error)setRegistrationEnabled(s.data?.value===true)}catch(e){setErr(friendly(e.message))}finally{setLoading(false)}}
useEffect(()=>{load()},[]);
async function action(payload){setBusy(true);setErr("");setSuccess("");try{const{data:{session}}=await db.auth.getSession();if(!session)throw new Error("unauthorized");const r=await fetch("https://jcblfgrcsgbdeamogzfc.supabase.co/functions/v1/admin-user-actions",{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||j.message||"server_error");await load();return true}catch(e){setErr(friendly(e.message));return false}finally{setBusy(false)}}
async function createUser(e){e.preventDefault();setErr("");setSuccess("");if(!form.username||!form.display_name||!form.password)return setErr("نام کاربری، نام نمایشی و رمز عبور را وارد کن.");const ok=await action({action:"create_user",username:form.username,display_name:form.display_name,password:form.password,role:form.role,is_verified:form.verification!=="none",verification:form.verification});if(ok){setForm({username:"",display_name:"",password:"",role:"user",verification:"none"});setSuccess("کاربر با موفقیت ساخته شد.");setTab("users")}}
async function setRegistration(enabled){setBusy(true);setErr("");setSuccess("");try{const{data:{user}}=await db.auth.getUser();const{error}=await db.from("app_settings").update({value:enabled,updated_at:new Date().toISOString(),updated_by:user.id}).eq("key","registration_enabled");if(error)throw error;setRegistrationEnabled(enabled);setSuccess(enabled?"ثبت‌نام عمومی روشن شد.":"ثبت‌نام عمومی خاموش شد.")}catch(e){setErr(friendly(e.message))}finally{setBusy(false)}}
async function setVerification(x,v){await action({action:"set_verification",user_id:x.id,verification:v,is_verified:v!=="none"})}
async function delMsg(x){if(!confirm("این پیام حذف شود؟"))return;setBusy(true);const{error}=await db.from("messages").delete().eq("id",x.id);if(error)setErr(error.message);else{await db.from("admin_logs").insert({admin_id:me.id,action:"delete_message",target_message_id:x.id});await load()}setBusy(false)}
async function userAction(x,a){if((a==="delete_user"||a==="ban")&&!confirm(`کاربر @${x.username} ${a==="ban"?"مسدود":"حذف"} شود؟`))return;if(a==="reset_password"){const p=prompt("رمز عبور جدید (حداقل ۶ کاراکتر):");if(p===null)return;if(p.length<6)return setErr("رمز عبور باید حداقل ۶ کاراکتر باشد.");return action({action:a,user_id:x.id,password:p})}if(a==="set_role")return action({action:a,user_id:x.id,role:x.role==="admin"?"user":"admin"});if(a==="set_verification")return setVerification(x,x.verification==="blue"?"none":"blue");return action({action:a,user_id:x.id})}
const stats=useMemo(()=>({users:users.length,admins:users.filter(x=>x.role==="admin").length,banned:users.filter(x=>x.is_banned).length,verified:users.filter(x=>x.verification&&x.verification!=="none").length}),[users]);
if(loading)return <main className="admin-shell"><div className="admin-loading">در حال بارگذاری پنل مدیریت…</div></main>;if(!me)return <main className="admin-shell"><div className="admin-card"><h1>403</h1><p>{err}</p><a href="/">بازگشت</a></div></main>;
return <main className="admin-shell" dir="rtl"><aside className="admin-sidebar"><div className="admin-brand"><strong>Utino Chat v1</strong><small>@{me.username} · Admin</small></div>{tabs.filter(([k])=>k!=="settings"||me.username?.toLowerCase()==="parham").map(([k,v])=><button type="button" className={tab===k?"active":""} onClick={()=>{setTab(k);setErr("");setSuccess("")}} key={k}>{v}</button>)}<button type="button" onClick={()=>location.href="/messenger/"}>بازگشت به پیام‌رسان</button><button type="button" onClick={async()=>{await db.auth.signOut();location.href="/"}}>خروج</button></aside><section className="admin-main"><header className="admin-header"><div><h1>{tabs.find(x=>x[0]===tab)?.[1]}</h1><span>کنترل مرکزی Utino Chat v1</span></div><button type="button" onClick={load} disabled={busy} aria-label="بازخوانی">↻</button></header>{err&&<div className="admin-error" role="alert">{friendly(err)}</div>}{success&&<div className="admin-success" role="status">{success}</div>}
{tab==="home"&&<div className="admin-grid"><div className="admin-stat"><b>{stats.users}</b><span>کل کاربران</span></div><div className="admin-stat"><b>{stats.admins}</b><span>ادمین‌ها</span></div><div className="admin-stat"><b>{stats.verified}</b><span>تأیید شده</span></div><div className="admin-stat"><b>{stats.banned}</b><span>مسدود</span></div><div className="admin-card"><h2>وضعیت سیستم</h2><p>Auth و Database متصل هستند.</p><p>RLS فعال است.</p><p>ساخت کاربر از سمت سرور انجام می‌شود.</p></div></div>}
{tab==="users"&&<div className="admin-card"><div className="admin-toolbar"><strong>{users.length} کاربر</strong><button type="button" className="admin-button primary" onClick={()=>setTab("create")}>+ ساخت کاربر</button></div><div className="admin-table-wrap"><table><thead><tr><th>کاربر</th><th>نام</th><th>نقش</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{users.map(x=><tr key={x.id}><td><b>@{x.username}</b><small>{x.public_id||""}</small></td><td>{x.display_name||"-"}</td><td>{x.role}</td><td><span className={`verify-badge ${x.verification||"none"}`}>✓ {badgeLabel(x.verification||"none")}</span>{x.is_banned&&<small>مسدود</small>}</td><td><div className="row-actions"><select disabled={busy} value={x.verification||"none"} onChange={e=>setVerification(x,e.target.value)}><option value="none">بدون تیک</option><option value="blue">🔵 تیک آبی</option><option value="green">🟢 تیک سبز</option><option value="orange">🟠 تیک نارنجی</option><option value="red">🔴 تیک قرمز</option></select><button type="button" disabled={busy||x.id===me.id} onClick={()=>userAction(x,"set_role")}>{x.role==="admin"?"کاربر":"ادمین"}</button><button type="button" disabled={busy} onClick={()=>userAction(x,"reset_password")}>رمز جدید</button><button type="button" disabled={busy||x.id===me.id} onClick={()=>userAction(x,x.is_banned?"unban":"ban")}>{x.is_banned?"رفع مسدودی":"مسدود"}</button>{x.id!==me.id&&<button type="button" disabled={busy} className="danger" onClick={()=>userAction(x,"delete_user")}>حذف</button>}</div></td></tr>)}</tbody></table></div></div>}
{tab==="create"&&<div className="admin-card form-card"><h2>ساخت کاربر جدید</h2><p className="muted">حساب بدون ثبت‌نام عمومی ساخته می‌شود.</p><form onSubmit={createUser}><label>نام کاربری<input required minLength={3} maxLength={20} pattern="[a-z0-9_]+" value={form.username} onChange={e=>setForm({...form,username:e.target.value.replace(/\s/g,"").toLowerCase()})} placeholder="username" autoComplete="off" /></label><label>نام نمایشی<input required maxLength={80} value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})} placeholder="نام کاربر" /></label><label>رمز عبور<input required minLength={6} maxLength={128} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="حداقل ۶ کاراکتر" autoComplete="new-password" /></label><label>نقش<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="user">کاربر</option><option value="admin">ادمین</option></select></label><label>نشان تأیید<select value={form.verification} onChange={e=>setForm({...form,verification:e.target.value})}><option value="none">بدون تیک</option><option value="blue">تیک آبی</option><option value="green">تیک سبز</option><option value="orange">تیک نارنجی</option><option value="red">تیک قرمز</option></select></label><div className="form-actions"><button type="submit" className="admin-button primary" disabled={busy}>{busy?"در حال ساخت…":"ساخت کاربر"}</button><button type="button" className="admin-button" onClick={()=>setTab("users")}>انصراف</button></div></form></div>}
{tab==="settings"&&me.username?.toLowerCase()==="parham"&&<div className="admin-card"><h2>تنظیمات اصلی</h2><p className="muted">فقط مالک @parham به این بخش دسترسی دارد.</p><div className="registration-setting"><div><strong>ثبت‌نام عمومی</strong><span>{registrationEnabled?"روشن":"خاموش"}</span></div><button type="button" className={`admin-button ${registrationEnabled?"danger":"primary"}`} disabled={busy} onClick={()=>setRegistration(!registrationEnabled)}>{registrationEnabled?"خاموش کردن":"روشن کردن"}</button></div></div>}
{tab==="messages"&&<div className="admin-card"><div className="admin-toolbar"><strong>{msgs.length} پیام اخیر</strong></div><div className="admin-table-wrap"><table><thead><tr><th>پیام</th><th>نوع</th><th>زمان</th><th></th></tr></thead><tbody>{msgs.map(x=><tr key={x.id}><td className="admin-content">{x.file_name||x.content||"فایل"}</td><td>{x.message_type}</td><td>{new Date(x.created_at).toLocaleString("fa-IR")}</td><td><button type="button" disabled={busy} className="danger" onClick={()=>delMsg(x)}>حذف</button></td></tr>)}</tbody></table></div></div>}{tab==="logs"&&<div className="admin-card"><div className="admin-table-wrap"><table><thead><tr><th>عملیات</th><th>هدف</th><th>زمان</th><th>جزئیات</th></tr></thead><tbody>{logs.map(x=><tr key={x.id}><td>{x.action}</td><td>{x.target_user_id||x.target_message_id||"-"}</td><td>{new Date(x.created_at).toLocaleString("fa-IR")}</td><td>{JSON.stringify(x.details||{})}</td></tr>)}</tbody></table></div></div>}{tab==="tickets"&&<div className="admin-card"><h2>پشتیبانی</h2><p>مدیریت تیکت‌ها از این بخش انجام می‌شود.</p><a className="admin-button" href="/admin/tickets/">باز کردن تیکت‌ها</a></div>}</section></main>}
