"use client";
import { useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";
const db=createClient("https://jcblfgrcsgbdeamogzfc.supabase.co","sb_publishable_9qBGewmR-UHx6Pc3_Gl36Q_7WhHCw2K",{auth:{persistSession:true,autoRefreshToken:true}});
export default function SupportChat(){
 const[chats,setChats]=useState([]),[users,setUsers]=useState({}),[selected,setSelected]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){setLoading(true);const{data,error:e}=await db.from("support_chats").select("id,user_id,status,created_at,updated_at").order("updated_at",{ascending:false});if(e){setError(e.message);setLoading(false);return}setChats(data||[]);const ids=[...new Set((data||[]).map(x=>x.user_id))];if(ids.length){const{data:p}=await db.from("profiles").select("id,username,display_name,public_id").in("id",ids);setUsers(Object.fromEntries((p||[]).map(x=>[x.id,x])))}setLoading(false)}
 async function open(c){setSelected(c);const{data,error:e}=await db.from("support_chat_messages").select("id,chat_id,sender_id,content,created_at").eq("chat_id",c.id).order("created_at",{ascending:true});if(e)setError(e.message);else setMessages(data||[])}
 async function send(){if(!selected||selected.status!=="open"||!text.trim()||busy)return;setBusy(true);const{data:{user}}=await db.auth.getUser();const{error:e}=await db.from("support_chat_messages").insert({chat_id:selected.id,sender_id:user.id,content:text.trim()});if(e)setError(e.message);else{setText("");await open(selected);await load()}setBusy(false)}
 async function close(){if(!selected||busy)return;setBusy(true);const{error:e}=await db.from("support_chats").update({status:"closed"}).eq("id",selected.id);if(e)setError(e.message);else{const n={...selected,status:"closed"};setSelected(n);await load()}setBusy(false)}
 useEffect(()=>{load()},[]);
 useEffect(()=>{const ch=db.channel("support-admin").on("postgres_changes",{event:"*",schema:"public",table:"support_chats"},()=>load()).on("postgres_changes",{event:"INSERT",schema:"public",table:"support_chat_messages"},()=>{load();if(selected)open(selected)}).subscribe();return()=>db.removeChannel(ch)},[selected?.id]);
 if(loading)return <div className="admin-card">در حال بارگذاری پشتیبانی…</div>;
 return <div className="admin-ticket-layout"><div className="admin-card admin-ticket-list"><div className="admin-toolbar"><strong>پشتیبانی مستقیم ({chats.length})</strong><button className="admin-button" onClick={load}>↻</button></div>{!chats.length?<p className="muted">هنوز گفتگویی با پشتیبانی شروع نشده.</p>:chats.map(c=><button className={'ticket-item '+(selected?.id===c.id?'active':'')} key={c.id} onClick={()=>open(c)}><div><b>{users[c.user_id]?.display_name||users[c.user_id]?.username||'کاربر'}</b><small>@{users[c.user_id]?.username||'unknown'}</small></div><span className={'ticket-status '+c.status}>{c.status==='open'?'باز':'پایان یافته'}</span></button>)}</div>{selected?<div className="admin-card admin-ticket-chat"><div className="ticket-head"><div><h2>پشتیبانی مستقیم</h2><p>@{users[selected.user_id]?.username||'unknown'}</p></div>{selected.status==='open'&&<button className="admin-button" onClick={close} disabled={busy}>پایان گفتگو</button>}</div><div className="ticket-messages">{messages.length?messages.map(m=><div className="ticket-message" key={m.id}><small>{m.sender_id===selected.user_id?'کاربر':'پشتیبانی'} · {new Date(m.created_at).toLocaleString('fa-IR')}</small><p>{m.content}</p></div>):<p className="muted">هنوز پیامی ارسال نشده.</p>}</div>{selected.status==='open'&&<div className="ticket-compose"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="پاسخ به کاربر…" maxLength={4000}/><button className="admin-button primary" onClick={send} disabled={busy||!text.trim()}>ارسال</button></div>}</div>:<div className="admin-card ticket-empty"><h2>یک گفتگوی پشتیبانی را انتخاب کن</h2><p className="muted">پیام‌های مستقیم کاربران اینجا نمایش داده می‌شود.</p></div>}</div>
}