"use client";
import { useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";
const db=createClient("https://jcblfgrcsgbdeamogzfc.supabase.co","sb_publishable_9qBGewmR-UHx6Pc3_Gl36Q_7WhHCw2K",{auth:{persistSession:true,autoRefreshToken:true}});
const statusLabel={open:"باز",pending:"در انتظار",closed:"بسته"};
const priorityLabel={low:"کم",normal:"عادی",high:"زیاد",urgent:"فوری"};
export default function SupportTickets(){
 const[tickets,setTickets]=useState([]),[selected,setSelected]=useState(null),[messages,setMessages]=useState([]),[users,setUsers]=useState({}),[text,setText]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");const{data,error:e}=await db.from("support_tickets").select("id,user_id,subject,status,priority,created_at,updated_at").order("updated_at",{ascending:false});if(e){setError(e.message);setLoading(false);return}setTickets(data||[]);const ids=[...new Set((data||[]).map(x=>x.user_id))];if(ids.length){const{data:p}=await db.from("profiles").select("id,username,display_name,public_id").in("id",ids);setUsers(Object.fromEntries((p||[]).map(x=>[x.id,x])))}setLoading(false)}
 async function openTicket(t){setSelected(t);const{data,error:e}=await db.from("support_ticket_messages").select("id,ticket_id,sender_id,content,created_at").eq("ticket_id",t.id).order("created_at",{ascending:true});if(e)setError(e.message);else setMessages(data||[])}
 async function send(){if(!selected||!text.trim()||busy)return;setBusy(true);setError("");const{data:{user}}=await db.auth.getUser();const{error:e}=await db.from("support_ticket_messages").insert({ticket_id:selected.id,sender_id:user.id,content:text.trim()});if(e)setError(e.message);else{setText("");await openTicket(selected);await load()}setBusy(false)}
 async function setStatus(status){if(!selected||busy)return;setBusy(true);const{error:e}=await db.from("support_tickets").update({status}).eq("id",selected.id);if(e)setError(e.message);else{const n={...selected,status};setSelected(n);await load()}setBusy(false)}
 useEffect(()=>{load()},[]);
 if(loading)return <div className="admin-card"><p>در حال بارگذاری تیکت‌ها…</p></div>;
 return <div className="admin-ticket-layout"><div className="admin-card admin-ticket-list"><div className="admin-toolbar"><strong>تیکت‌ها ({tickets.length})</strong><button type="button" className="admin-button" onClick={load}>↻</button></div>{error&&<div className="admin-error">{error}</div>}{!tickets.length?<p className="muted">هنوز تیکتی ثبت نشده است.</p>:tickets.map(t=><button type="button" key={t.id} className={`ticket-item ${selected?.id===t.id?"active":""}`} onClick={()=>openTicket(t)}><div><b>{t.subject}</b><small>@{users[t.user_id]?.username||"unknown"}</small></div><span className={`ticket-status ${t.status}`}>{statusLabel[t.status]}</span></button>)}</div>{selected?<div className="admin-card admin-ticket-chat"><div className="ticket-head"><div><h2>{selected.subject}</h2><p>@{users[selected.user_id]?.username||"unknown"} · {priorityLabel[selected.priority]}</p></div><select value={selected.status} disabled={busy} onChange={e=>setStatus(e.target.value)}><option value="open">باز</option><option value="pending">در انتظار</option><option value="closed">بسته</option></select></div><div className="ticket-messages">{messages.map(m=><div className="ticket-message" key={m.id}><small>{m.sender_id===selected.user_id?"کاربر":"پشتیبانی"} · {new Date(m.created_at).toLocaleString("fa-IR")}</small><p>{m.content}</p></div>)}</div><div className="ticket-compose"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="پاسخ به تیکت..." maxLength={4000}/><button type="button" className="admin-button primary" disabled={busy||!text.trim()} onClick={send}>ارسال</button></div></div>:<div className="admin-card ticket-empty"><h2>یک تیکت را انتخاب کن</h2><p className="muted">پیام‌های کاربر اینجا نمایش داده می‌شوند.</p></div>}</div>
}