"use client";
import{useEffect,useState}from"react";import{createClient}from"@supabase/supabase-js";import mapError from"../lib/error-map";
const db=createClient("https://jcblfgrcsgbdeamogzfc.supabase.co","sb_publishable_9qBGewmR-UHx6Pc3_Gl36Q_7WhHCw2K");
export default function SupportInbox(){const[chats,setChats]=useState([]),[profiles,setProfiles]=useState({}),[selected,setSelected]=useState(null),[ms,setMs]=useState([]),[v,setV]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
const load=async()=>{setError("");const{data,error:e}=await db.from("support_chats").select("id,user_id,status,updated_at").order("updated_at",{ascending:false});if(e){setError(mapError(e));return}setChats(data||[]);const ids=[...new Set((data||[]).map(x=>x.user_id).filter(Boolean))];if(ids.length){const{data:p,error:pe}=await db.rpc("get_public_profiles",{p_user_ids:ids});if(pe){setError(mapError(pe));return}setProfiles(Object.fromEntries((p||[]).map(x=>[x.id,x])))}else setProfiles({});if(selected)await loadMessages(selected)};
const loadMessages=async id=>{const{data,error:e}=await db.from("support_chat_messages").select("id,sender_id,content,created_at").eq("chat_id",id).order("created_at");if(e)setError(mapError(e));else setMs(data||[])};
useEffect(()=>{load()},[]);useEffect(()=>{if(!selected)return;loadMessages(selected);const c=db.channel("support-admin-"+selected).on("postgres_changes",{event:"*",schema:"public",table:"support_chat_messages",filter:"chat_id=eq."+selected},()=>{loadMessages(selected);load()}).on("postgres_changes",{event:"*",schema:"public",table:"support_chats"},load).subscribe();return()=>db.removeChannel(c)},[selected]);
const send=async()=>{const value=v.trim();if(!value||value.length>4000||!selected||busy)return;setBusy(true);setError("");const{data:{session}}=await db.auth.getSession();if(!session){setError(mapError("not_authenticated"));setBusy(false);return}const{error:e}=await db.from("support_chat_messages").insert({chat_id:selected,sender_id:session.user.id,content:value});if(e)setError(mapError(e));else{setV("");await loadMessages(selected);await load()}setBusy(false)};
const close=async()=>{if(!selected||busy)return;setBusy(true);const{error:e}=await db.rpc("close_support_chat",{chat_uuid:selected});if(e)setError(mapError(e));else await load();setBusy(false)};
return <section dir="rtl" style={{display:"grid",gridTemplateColumns:"280px 1fr",gap:12,minHeight:500}}><aside style={{border:"1px solid #ffffff12",borderRadius:14,overflow:"auto"}}>{error&&<div className="admin-error">{error}</div>}{chats.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} style={{display:"block",width:"100%",padding:12,textAlign:"right",background:selected===c.id?"#ffffff12":"transparent",color:"inherit",border:0,borderBottom:"1px solid #ffffff08"}}><b>{profiles[c.user_id]?.display_name||profiles[c.user_id]?.username||c.user_id.slice(0,8)}</b><small style={{display:"block",opacity:.6}}>{c.status==="closed"?"پایان یافته":"فعال"}</small></button>)}</aside><div style={{border:"1px solid #ffffff12",borderRadius:14,display:"flex",flexDirection:"column"}}>{!selected?<div style={{margin:"auto",opacity:.6}}>یک گفتگوی پشتیبانی را انتخاب کنید.</div>:<><div style={{padding:12,borderBottom:"1px solid #ffffff12",display:"flex",justifyContent:"space-between"}}><b>{profiles[chats.find(c=>c.id===selected)?.user_id]?.display_name||"کاربر"}</b><button disabled={busy} onClick={close}>پایان گفتگو</button></div><div style={{flex:1,overflow:"auto",padding:14}}>{ms.map(m=><div key={m.id} style={{padding:9,margin:"6px 0",background:"#ffffff08",borderRadius:12}}>{m.content}<small style={{display:"block",opacity:.5}}>{new Date(m.created_at).toLocaleString("fa-IR")}</small></div>)}</div><div style={{display:"flex",gap:8,padding:10}}><input style={{flex:1}} value={v} maxLength={4000} onChange={e=>setV(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="پاسخ..."/><button disabled={busy||!v.trim()} onClick={send}>ارسال</button></div></>}</div></section>}
