import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Menu,Search,MoreVertical,Paperclip,Smile,Send,ArrowLeft,CheckCheck,Settings,LogOut,Users,Archive,X,Shield,MessageCircle,Plus,Pin,User,Palette,Bell,Info,VolumeX,Trash2,UserPlus,Lock,Save,Reply,Copy,Check,ChevronDown,Folder,Bookmark,Download,Command,PanelRight,AtSign,Image as ImageIcon,Mic,Globe2}from'lucide-react';
import{supabase}from'./lib/supabase';
import'./styles.css';
import'./telegram-enhancements.css';

const initial=n=>(n||'U').trim().slice(0,1).toUpperCase();
const LS={settings:'utino-settings',folders:'utino-folders',chat:'utino-chat-state',saved:'utino-saved'};
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function Avatar({name,small}){return <div className={'avatar '+(small?'small':'')}>{initial(name)}</div>}
function NetworkError(){return <div className="error">ارتباط با سرور برقرار نشد. اتصال اینترنت و تنظیمات Supabase را بررسی کنید.</div>}
function App(){const path=location.pathname,[session,setSession]=useState(null),[authLoading,setAuthLoading]=useState(true);useEffect(()=>{let alive=true;(async()=>{try{const r=await supabase.auth.getSession();if(alive)setSession(r.data.session||null)}catch{}finally{if(alive)setAuthLoading(false)}})();const x=supabase.auth.onAuthStateChange((_,s)=>setSession(s));return()=>{alive=false;x.data.subscription.unsubscribe()}},[]);if(authLoading)return <div className="splash"><MessageCircle/><span>utinochat</span></div>;if(path==='/login'||path==='/signup')return session?<Messenger/>:<Auth signup={path==='/signup'}/>;return session?<Messenger/>:<Landing/>}
function Landing(){return <main className="landing"><header><div className="logo"><span>✦</span>utinochat</div><nav><a href="#features">ویژگی‌ها</a><a href="#platform">پلتفرم</a><a href="/login">ورود</a><a className="topbtn" href="/signup">شروع</a></nav></header><section className="hero"><div><div className="eyebrow">پیام‌رسان وب مدرن</div><h1>گفتگو،<br/><b>ساده و سریع.</b></h1><p>پیام‌رسان وب چندلایه با چت لحظه‌ای، اعلان مرورگر، پوشه‌ها، جست‌وجوی پیام و تجربه‌ای نزدیک به کلاینت‌های حرفه‌ای.</p><div className="actions"><a className="primary" href="/signup">ساخت حساب <ArrowLeft size={17}/></a><a className="secondary" href="/login">ورود</a></div></div><Mock/></section><section id="features" className="section"><small>ویژگی‌ها</small><h2>یک پوسته وب، با امکانات واقعی.</h2><div className="grid">{[['⚡','سریع','تعامل فوری و رابط سبک'],['🔔','اعلان وب','اعلان پیام‌های جدید در مرورگر'],['🗂','پوشه‌ها','همه، خوانده‌نشده، آرشیو و پوشه‌های شخصی'],['⌕','جست‌وجوی پیشرفته','جست‌وجوی گفتگو و فیلتر متن پیام'],['🔒','خصوصی','احراز هویت و کنترل دسترسی با Supabase'],['📱','Responsive','تجربه دو ستونه دسکتاپ و تک‌ستونه موبایل'],['↩','Reply / Copy','منوی پیام و پاسخ سریع'],['📌','Pin / Mute','کنترل محلی گفتگوها بدون دستکاری داده اصلی'],['☁','Realtime','همگام‌سازی پیام با Supabase Realtime']].map(x=><article key={x[1]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section><section id="platform" className="platform"><div><small>تجربه</small><h2>Web · PWA · Mobile</h2><p>قابلیت‌های قابل پیاده‌سازی در وب از پروژه‌های Telegram Web و Desktop به‌صورت مستقل و متناسب با معماری Supabase.</p></div><div className="chips"><b>Realtime</b><b>Notifications</b><b>Folders</b><b>Dark Mode</b><b>PWA</b><b>Supabase</b></div></section><footer><div className="footerlinks"><a href="https://wdner.co" target="_blank" rel="noreferrer">ودنر <span>WDNER</span></a><a href="https://iparham.com" target="_blank" rel="noreferrer">پرهام سلیمانی <span>iparham.com</span></a><a href="https://utino.org" target="_blank" rel="noreferrer">یوتینو <span>utino.org</span></a></div><div>© 2026 utinochat <span>Web Messenger</span></div></footer></main>}
function Mock(){return <div className="mock"><aside><div className="msearch"><Search size={15}/>جست‌وجو</div>{[['Utinochat','پیام‌رسانی سریع'],['Community','آخرین پیام'],['Saved Messages','پیام‌های ذخیره‌شده']].map((d,i)=><div className={'mrow '+(!i?'active':'')} key={d[0]}><Avatar name={d[0]} small/><div><b>{d[0]}</b><small>{d[1]}</small></div><time>12:40</time></div>)}</aside><div className="mchat"><div className="mhead"><Avatar name="Utinochat" small/><div><b>Utinochat</b><small>online</small></div></div><div className="wall"><em>امروز</em><p>سلام 👋</p><p className="out">پوشه‌ها و اعلان‌ها آماده‌اند.</p><p>جست‌وجو، Reply و Realtime.</p></div><div className="mcompose">پیام...<Send size={15}/></div></div></div>}
function Auth({signup}){const[email,setEmail]=useState(''),[loginId,setLoginId]=useState(''),[password,setPassword]=useState(''),[username,setUsername]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(signup){if(!/^[A-Za-z0-9_]{3,20}$/.test(username))throw Error('نام کاربری باید ۳ تا ۲۰ کاراکتر باشد.');const r=await supabase.auth.signUp({email,password});if(r.error)throw r.error;if(r.data.user){const p=await supabase.from('profiles').update({username,display_name:username}).eq('id',r.data.user.id);if(p.error)throw p.error}}else{const key=loginId.trim();if(!/^[A-Za-z0-9_]{3,40}$/.test(key))throw Error('شناسه یا نام کاربری معتبر نیست.');const r=await supabase.rpc('resolve_login_email',{login_id:key});if(r.error)throw r.error;if(!r.data)throw Error('شناسه یا نام کاربری پیدا نشد.');const s=await supabase.auth.signInWithPassword({email:r.data,password});if(s.error)throw s.error}}catch(e){setError(e?.message==='Failed to fetch'?'ارتباط با سرور برقرار نشد. تنظیمات Supabase یا اتصال اینترنت را بررسی کنید.':e?.message||'خطای ناشناخته')}finally{setBusy(false)}}return <main className="auth"><a className="logo" href="/"><span>✦</span>utinochat</a><div className="authcard"><div className="authico"><MessageCircle/></div><h1>{signup?'ساخت حساب':'ورود به utinochat'}</h1><p>{signup?'حساب خودت را بساز.':'با شناسه یا نام کاربری وارد شو.'}</p><form onSubmit={submit}>{signup&&<label>نام کاربری<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="مثلاً utino_user" autoComplete="username" required/></label>}{signup&&<label>ایمیل<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label>}{!signup&&<label>شناسه / نام کاربری<input value={loginId} onChange={e=>setLoginId(e.target.value)} placeholder="مثلاً utino_user" autoCapitalize="none" autoComplete="username" required/></label>}<label>رمز عبور<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength="6" autoComplete={signup?'new-password':'current-password'} required/></label>{error&&(error.includes('ارتباط با سرور')?<NetworkError/>:<div className="error">{error}</div>)}<button className="primary full" disabled={busy}>{busy?'در حال پردازش...':signup?'ثبت نام':'ورود'}<ArrowLeft size={17}/></button></form><a className="switch" href={signup?'/login':'/signup'}>{signup?'حساب دارید؟ ورود':'حساب ندارید؟ ثبت نام'}</a></div></main>}
function Messenger(){const[profile,setProfile]=useState(null),[chats,setChats]=useState([]),[selected,setSelected]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[search,setSearch]=useState(''),[folder,setFolder]=useState('all'),[drawer,setDrawer]=useState(false),[dark,setDark]=useState(localStorage.getItem('utino-dark')==='1'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[panel,setPanel]=useState(null),[menu,setMenu]=useState(false),[newChat,setNewChat]=useState(false),[directory,setDirectory]=useState(''),[users,setUsers]=useState([]),[userBusy,setUserBusy]=useState(false),[settings,setSettings]=useState(()=>read(LS.settings,{enterSend:true,notifications:true,compact:false,animations:true})),[chatState,setChatState]=useState(()=>read(LS.chat,{})),[customFolders,setCustomFolders]=useState(()=>read(LS.folders,[])),[replyTo,setReplyTo]=useState(null),[messageMenu,setMessageMenu]=useState(null),[infoOpen,setInfoOpen]=useState(false),[notice,setNotice]=useState('');const end=useRef(),inputRef=useRef();
useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('utino-dark',dark?'1':'0')},[dark]);
useEffect(()=>{localStorage.setItem(LS.settings,JSON.stringify(settings))},[settings]);useEffect(()=>{localStorage.setItem(LS.chat,JSON.stringify(chatState))},[chatState]);useEffect(()=>{localStorage.setItem(LS.folders,JSON.stringify(customFolders))},[customFolders]);
useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})},[]);
useEffect(()=>{(async()=>{try{const p=await supabase.rpc('get_my_profile');if(p.error)throw p.error;setProfile(p.data?.[0]||null);const s=await supabase.auth.getSession();if(s.data.session)await load(s.data.session.user.id)}catch(e){setError(e?.message==='Failed to fetch'?'ارتباط با سرور برقرار نشد.':e?.message||'خطا در بارگذاری')}finally{setLoading(false)}})()},[]);
async function load(uid){const m=await supabase.from('conversation_members').select('conversation_id').eq('user_id',uid);if(m.error)throw m.error;const ids=(m.data||[]).map(x=>x.conversation_id);if(!ids.length)return setChats([]);const c=await supabase.from('conversations').select('*').in('id',ids).order('created_at',{ascending:false});if(c.error)throw c.error;setChats(c.data||[])}
useEffect(()=>{if(!selected)return;let live=true;(async()=>{const r=await supabase.from('messages').select('*').eq('conversation_id',selected.id).is('deleted_at',null).order('created_at').limit(300);if(live){if(r.error)setError(r.error.message);else{setMessages(r.data||[]);const ids=(r.data||[]).filter(m=>m.sender_id!==profile?.id).map(m=>m.id);if(ids.length)await supabase.rpc('mark_messages_seen',{message_ids:ids});setChatState(s=>({...s,[selected.id]:{...(s[selected.id]||{}),unread:0}}))}setTimeout(()=>end.current?.scrollIntoView({behavior:settings.animations?'smooth':'auto'}),30)}})();const c=supabase.channel('chat-'+selected.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${selected.id}`},p=>{setMessages(v=>v.some(m=>m.id===p.new.id)?v:[...v,p.new]);if(p.new.sender_id!==profile?.id){setChatState(s=>({...s,[selected.id]:{...(s[selected.id]||{}),unread:(s[selected.id]?.unread||0)+1}}));if(settings.notifications&&document.visibilityState!=='visible'&&'Notification'in window&&Notification.permission==='granted')new Notification(selected.title||'پیام جدید',{body:p.new.content||'پیام جدید'})}}).subscribe();return()=>{live=false;supabase.removeChannel(c)}},[selected?.id,profile?.id,settings.notifications,settings.animations]);
useEffect(()=>{const fn=e=>{if(e.key==='Escape'){setMenu(false);setMessageMenu(null);setPanel(null)}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector('.search input')?.focus()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();inputRef.current?.focus()}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[]);
async function send(){if(!text.trim()||!selected||!profile)return;const v=text.trim();setText('');setError('');const r=await supabase.rpc('send_message',{p_conversation_id:selected.id,p_content:v,p_message_type:'text'});if(r.error){setText(v);setError(r.message==='not_conversation_member'?'شما عضو این گفتگو نیستید.':r.error.message||'ارسال پیام انجام نشد.')}else setReplyTo(null)}
async function searchUsers(){const q=directory.trim();if(!q)return setUsers([]);setUserBusy(true);try{const r=await supabase.rpc('search_user_directory',{search_text:q,result_limit:12});if(r.error)throw r.error;setUsers(r.data||[])}catch(e){setError(e?.message||'جست‌وجوی کاربر انجام نشد.')}finally{setUserBusy(false)}}
async function openDirect(u){setUserBusy(true);try{const r=await supabase.rpc('get_or_create_direct_conversation',{other_user_id:u.id});if(r.error)throw r.error;await load(profile.id);const found=await supabase.from('conversations').select('*').eq('id',r.data).maybeSingle();if(found.error)throw found.error;if(found.data){setSelected(found.data);setPanel(null);setNewChat(false)}}catch(e){setError(e?.message||'ساخت گفتگوی خصوصی انجام نشد.')}finally{setUserBusy(false)}}
async function saveProfile(){const name=panel?.name??profile?.display_name??profile?.username??'',bio=panel?.bio??profile?.bio??'';const r=await supabase.rpc('update_my_profile',{new_display_name:name,new_bio:bio});if(r.error)setError(r.error.message);else{setProfile({...profile,display_name:name,bio});setPanel(null)}}
function patchChat(id,patch){setChatState(s=>({...s,[id]:{...(s[id]||{}),...patch}}));setMenu(false)}
async function askNotifications(){if(!('Notification'in window)){setNotice('این مرورگر اعلان وب را پشتیبانی نمی‌کند.');return}const p=await Notification.requestPermission();setSettings(s=>({...s,notifications:p==='granted'}));setNotice(p==='granted'?'اعلان‌ها فعال شد.':'اجازه اعلان داده نشد.');setTimeout(()=>setNotice(''),2200)}
function chooseMessage(m){setMessageMenu(null);setReplyTo(m);inputRef.current?.focus()}
function copyMessage(m){navigator.clipboard?.writeText(m.content||'');setNotice('متن پیام کپی شد.');setTimeout(()=>setNotice(''),1600);setMessageMenu(null)}
function hideMessage(m){setMessages(v=>v.filter(x=>x.id!==m.id));setNotice('پیام از این نمایش حذف شد.');setTimeout(()=>setNotice(''),1600);setMessageMenu(null)}
const visible=useMemo(()=>chats.filter(c=>{const st=chatState[c.id]||{};const title=(c.title||'گفتگوی خصوصی').toLowerCase();if(!title.includes(search.toLowerCase()))return false;if(folder==='unread'&&!(st.unread>0))return false;if(folder==='archive'&&!st.archived)return false;if(folder!=='all'&&folder!=='unread'&&folder!=='archive'&&st.folder!==folder)return false;return !st.hidden}),[chats,search,folder,chatState]);
const title=selected?.title||'گفتگوی خصوصی';const selectedState=selected?(chatState[selected.id]||{}):{};
return <div className={'messenger '+(settings.compact?'compact':'')}>
<aside className={'sidebar '+(selected?'hasselection':'')}><div className="sidehead"><button className="icon" title="منو" onClick={()=>setDrawer(v=>!v)}><Menu/></button><div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جست‌وجو"/><kbd>Ctrl K</kbd></div></div>
<div className="tabs">{[['all','همه'],['unread','خوانده‌نشده'],['archive','آرشیو'],...customFolders.map(f=>[f.id,f.name])].map(([id,n])=><button key={id} className={folder===id?'active':''} onClick={()=>setFolder(id)}>{n}{id==='unread'&&Object.values(chatState).reduce((a,x)=>a+(x.unread||0),0)>0&&<b className="tabbadge">{Object.values(chatState).reduce((a,x)=>a+(x.unread||0),0)}</b>}</button>)}</div>
<div className="chatlist">{loading?[1,2,3,4,5].map(i=><div className="skeleton" key={i}/>):visible.map(c=>{const st=chatState[c.id]||{};return <button className={'chatitem '+(selected?.id===c.id?'selected':'')} key={c.id} onClick={()=>{setSelected(c);setMessages([]);setError('');setMenu(false)}}><Avatar name={c.title}/><div><strong>{c.title||'گفتگوی خصوصی'}</strong><small>{st.muted&&'🔕 '}{st.pinned&&'📌 '}{st.last||'آخرین پیام'}</small></div><span className="chatmeta">{st.unread>0&&<b>{st.unread}</b>}{st.pinned&&<Pin size={13}/>}</span></button>})}{!loading&&!visible.length&&<div className="empty"><Folder/><b>گفتگویی پیدا نشد</b><span>جست‌وجو یا پوشه دیگری را امتحان کن.</span><button className="newchat" onClick={()=>setNewChat(true)}><Plus size={15}/> گفتگوی جدید</button></div>}</div>
<div className="sidebottom"><button onClick={()=>setNewChat(true)}><Plus/> جدید</button><button onClick={()=>setPanel({type:'settings'})}><Settings/> تنظیمات</button></div>
{drawer&&<div className="drawer"><button className="drawerprofilebtn" onClick={()=>{setPanel({type:'profile',name:profile?.display_name||profile?.username||'',bio:profile?.bio||''});setDrawer(false)}}><div className="drawerprofile"><Avatar name={profile?.display_name||profile?.username}/><div><b>{profile?.display_name||profile?.username||'کاربر'}</b><small>@{profile?.username||'user'}</small></div></div></button><button onClick={()=>setPanel({type:'saved'})}><Bookmark/> پیام‌های ذخیره‌شده</button><button onClick={()=>setPanel({type:'folders'})}><Folder/> پوشه‌ها</button><button onClick={()=>setPanel({type:'notifications'})}><Bell/> اعلان‌ها</button><button onClick={()=>setPanel({type:'privacy'})}><Shield/> حریم خصوصی</button><button onClick={()=>setPanel({type:'about'})}><Info/> درباره utinochat</button><button onClick={()=>supabase.auth.signOut()}><LogOut/> خروج</button></div>}
</aside>
<main className="chat">{selected?<><header className="chathead"><button className="icon back" onClick={()=>setSelected(null)}><ArrowLeft/></button><Avatar name={title}/><button className="chatnamebtn" onClick={()=>setInfoOpen(v=>!v)}><div className="chatname"><b>{title}</b><small>{selectedState.muted?'اعلان‌ها خاموش':'گفتگو · آنلاین'}</small></div></button><div className="chattools"><button title="جست‌وجوی پیام" onClick={()=>setNotice('جست‌وجوی پیام با Ctrl+K انجام می‌شود.')}><Search/></button><button title="اطلاعات" onClick={()=>setInfoOpen(v=>!v)}><Info/></button><button title="بیشتر" onClick={()=>setMenu(v=>!v)}><MoreVertical/></button></div>{menu&&<div className="contextmenu"><button onClick={()=>patchChat(selected.id,{pinned:!selectedState.pinned})}><Pin/>{selectedState.pinned?'برداشتن سنجاق':'سنجاق گفتگو'}</button><button onClick={()=>patchChat(selected.id,{muted:!selectedState.muted})}><VolumeX/>{selectedState.muted?'فعال کردن اعلان':'بی‌صدا کردن'}</button><button onClick={()=>patchChat(selected.id,{archived:!selectedState.archived})}><Archive/>{selectedState.archived?'بازگردانی از آرشیو':'انتقال به آرشیو'}</button><button onClick={()=>patchChat(selected.id,{hidden:true})}><Trash2/>حذف از فهرست من</button></div>}</header>
{selectedState.muted&&<div className="networkbar"><VolumeX size={14}/>اعلان‌های این گفتگو خاموش است.<button onClick={()=>patchChat(selected.id,{muted:false})}>فعال‌سازی</button></div>}
<div className="messages">{messages.map((m,i)=>{const mine=m.sender_id===profile?.id;return <div className={'msgrow '+(mine?'mine':'')} key={m.id} onContextMenu={e=>{e.preventDefault();setMessageMenu({x:e.clientX,y:e.clientY,m})}}><div className="bubble">{replyTo&&false}<div>{m.content}</div><small>{new Date(m.created_at).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})}{mine&&<CheckCheck size={13}/>}</small></div></div>})}<div ref={end}/></div>
{replyTo&&<div className="replybar"><Reply size={15}/><div><b>پاسخ به پیام</b><span>{replyTo.content}</span></div><button onClick={()=>setReplyTo(null)}><X/></button></div>}
<div className="composer"><button title="پیوست"><Paperclip/></button><input ref={inputRef} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&settings.enterSend){e.preventDefault();send()}}} placeholder="پیام..."/><button title="ایموجی"><Smile/></button><button className="send" onClick={send}><Send/></button></div>
{messageMenu&&<div className="message-menu" style={{left:Math.min(messageMenu.x,window.innerWidth-220),top:Math.min(messageMenu.y,window.innerHeight-150)}}><button onClick={()=>chooseMessage(messageMenu.m)}><Reply/>پاسخ</button><button onClick={()=>copyMessage(messageMenu.m)}><Copy/>کپی</button><button onClick={()=>hideMessage(messageMenu.m)}><Trash2/>حذف از نمایش</button></div>}
{infoOpen&&<aside className="info-panel"><button className="panelclose" onClick={()=>setInfoOpen(false)}><X/></button><Avatar name={title}/><h3>{title}</h3><p>{selectedState.muted?'اعلان‌ها خاموش':'اعلان‌ها روشن'}</p><div className="infoblocks"><button onClick={()=>patchChat(selected.id,{pinned:!selectedState.pinned})}><Pin/> {selectedState.pinned?'Unpin':'Pin'}</button><button onClick={()=>patchChat(selected.id,{muted:!selectedState.muted})}><VolumeX/> {selectedState.muted?'Unmute':'Mute'}</button><button onClick={()=>setPanel({type:'searchMessages',chat:selected})}><Search/> جست‌وجوی پیام</button></div></aside>}
</>:<div className="welcome"><div className="welcomeico"><MessageCircle/></div><h2>utinochat</h2><p>یک گفت‌وگو را انتخاب کن یا گفتگوی جدید بساز.</p><button className="welcomeNew" onClick={()=>setNewChat(true)}><Plus/> گفتگوی جدید</button></div>}
</main>
{panel&&<Panel panel={panel} setPanel={setPanel} profile={profile} setProfile={setProfile} saveProfile={saveProfile} settings={settings} setSettings={setSettings} askNotifications={askNotifications} dark={dark} setDark={setDark} customFolders={customFolders} setCustomFolders={setCustomFolders}/>} {newChat&&<NewChat directory={directory} setDirectory={setDirectory} users={users} searchUsers={searchUsers} userBusy={userBusy} openDirect={openDirect} close={()=>setNewChat(false)}/>} {notice&&<div className="toast">{notice}</div>}{error&&<div className="floating-error" onClick={()=>setError('')}>{error}<X size={14}/></div>}
</div>}
function Panel({panel,setPanel,profile,setProfile,saveProfile,settings,setSettings,askNotifications,dark,setDark,customFolders,setCustomFolders}){const[pname,setPname]=useState(panel.name||''),[pbio,setPbio]=useState(panel.bio||''),[folderName,setFolderName]=useState('');if(panel.type==='profile')return <div className="modalshade"><div className="modal"><div className="modalhead"><b>پروفایل</b><button onClick={()=>setPanel(null)}><X/></button></div><div className="profilebig"><Avatar name={pname}/><b>@{profile?.username||'user'}</b></div><label>نام نمایشی<input value={pname} onChange={e=>setPname(e.target.value)}/></label><label>بیوگرافی<textarea value={pbio} onChange={e=>setPbio(e.target.value)}/></label><button className="primary full" onClick={()=>{setProfile({...profile,display_name:pname,bio:pbio});saveProfile()}}><Save/> ذخیره</button></div></div>;
if(panel.type==='settings'||panel.type==='notifications')return <div className="modalshade"><div className="modal"><div className="modalhead"><b>{panel.type==='notifications'?'اعلان‌ها':'تنظیمات'}</b><button onClick={()=>setPanel(null)}><X/></button></div><SettingRow icon={<Bell/>} title="اعلان‌های مرورگر" text="برای پیام‌های جدید اعلان نمایش بده" on={settings.notifications} onClick={askNotifications}/><SettingRow icon={<Send/>} title="Enter برای ارسال" text="Enter پیام را ارسال کند" on={settings.enterSend} onClick={()=>setSettings(s=>({...s,enterSend:!s.enterSend}))}/><SettingRow icon={<Palette/>} title="تم تاریک" text="ظاهر تیره برای شب" on={dark} onClick={()=>setDark(v=>!v)}/><SettingRow icon={<Command/>} title="رابط فشرده" text="فاصله کمتر در فهرست گفتگوها" on={settings.compact} onClick={()=>setSettings(s=>({...s,compact:!s.compact}))}/><SettingRow icon={<Globe2/>} title="زبان" text="ساختار برای فارسی و انگلیسی آماده است" on={false} disabled/></div></div>;
if(panel.type==='folders')return <div className="modalshade"><div className="modal"><div className="modalhead"><b>پوشه‌های گفتگو</b><button onClick={()=>setPanel(null)}><X/></button></div><p className="hint">پوشه‌های شخصی در مرورگر ذخیره می‌شوند و می‌توانند برای دسته‌بندی گفتگوها استفاده شوند.</p><div className="folderadd"><input value={folderName} onChange={e=>setFolderName(e.target.value)} placeholder="نام پوشه، مثلاً کار"/><button onClick={()=>{if(folderName.trim()){setCustomFolders(v=>[...v,{id:'f_'+Date.now(),name:folderName.trim()}]);setFolderName('')}}}><Plus/></button></div>{customFolders.map(f=><div className="folderline" key={f.id}><Folder/><span>{f.name}</span><button onClick={()=>setCustomFolders(v=>v.filter(x=>x.id!==f.id))}><Trash2/></button></div>)}</div></div>;
if(panel.type==='saved')return <div className="modalshade"><div className="modal"><div className="modalhead"><b>پیام‌های ذخیره‌شده</b><button onClick={()=>setPanel(null)}><X/></button></div><div className="empty smallempty"><Bookmark/><span>پیام ذخیره‌شده‌ای هنوز ساخته نشده است.</span></div></div></div>;
if(panel.type==='privacy')return <div className="modalshade"><div className="modal"><div className="modalhead"><b>حریم خصوصی و امنیت</b><button onClick={()=>setPanel(null)}><X/></button></div><div className="securitycard"><Shield/><b>احراز هویت</b><span>ورود با Supabase Auth و دسترسی داده‌ها با RLS انجام می‌شود.</span></div><div className="securitycard"><Lock/><b>پیام‌ها</b><span>ارسال پیام از مسیر RPC امن پروژه انجام می‌شود.</span></div></div></div>;
if(panel.type==='about')return <div className="modalshade"><div className="modal"><div className="modalhead"><b>درباره utinochat</b><button onClick={()=>setPanel(null)}><X/></button></div><div className="about"><MessageCircle/><h2>utinochat</h2><p>پیام‌رسان وب مستقل با الهام از الگوهای UX کلاینت‌های مدرن.</p><small>Telegram Web K · Telegram Web A · Webogram · Telegram Desktop</small></div></div></div>;
return null}
function SettingRow({icon,title,text,on,onClick,disabled}){return <button className={'settingrow '+(disabled?'disabled':'')} onClick={onClick}><span className="settingicon">{icon}</span><span><b>{title}</b><small>{text}</small></span><i className={'switcher '+(on?'on':'')}>{on?'✓':''}</i></button>}
function NewChat({directory,setDirectory,users,searchUsers,userBusy,openDirect,close}){return <div className="modalshade"><div className="modal"><div className="modalhead"><b>گفتگوی جدید</b><button onClick={close}><X/></button></div><div className="modalsearch"><Search/><input autoFocus value={directory} onChange={e=>setDirectory(e.target.value)} onKeyDown={e=>e.key==='Enter'&&searchUsers()} placeholder="نام کاربری یا شناسه عمومی"/><button onClick={searchUsers}>{userBusy?'...':'جست‌وجو'}</button></div><div className="userresults">{users.map(u=><button className="userrow" key={u.id} onClick={()=>openDirect(u)}><Avatar name={u.display_name||u.username}/><span><b>{u.display_name||u.username}</b><small>@{u.username||u.public_id}</small></span><UserPlus/></button>)}{!users.length&&!userBusy&&<div className="empty smallempty"><Users/><span>کاربری پیدا نشده است.</span></div>}</div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
