create or replace function public.create_channel_conversation(channel_title text, channel_description text, channel_username text, channel_public boolean) returns uuid language plpgsql security definer set search_path=public,private as $$ declare me uuid:=auth.uid(); cid uuid; uname text; tok text; begin if me is null then raise exception 'not_authenticated'; end if; if coalesce(length(trim(channel_title)),0)<1 or length(trim(channel_title))>80 then raise exception 'invalid_channel_title'; end if; if coalesce(length(trim(channel_description)),0)>500 then raise exception 'invalid_channel_description'; end if; uname:=nullif(lower(trim(channel_username)),''); if uname is not null and uname !~ '^[a-z0-9_]{3,32}$' then raise exception 'invalid_channel_username'; end if; if uname is not null and exists(select 1 from public.profiles where lower(username)=uname) then raise exception 'channel_username_conflict'; end if; if uname is not null and exists(select 1 from public.channels where lower(username)=uname) then raise exception 'channel_username_conflict'; end if; tok:=encode(gen_random_bytes(18),'hex'); insert into public.conversations(type,title,created_by,is_channel,description,channel_username,is_public,discoverable,badge,invite_token) values('group',trim(channel_title),me,true,nullif(trim(channel_description),''),uname,coalesce(channel_public,false),coalesce(channel_public,false),'none',tok) returning id into cid; insert into public.conversation_members(conversation_id,user_id,role) values(cid,me,'owner'); insert into public.channels(id,owner_id,title,username,description,is_public,invite_token,badge) values(cid,me,trim(channel_title),uname,coalesce(trim(channel_description),''),coalesce(channel_public,false),tok,'none'); return cid; end $$;

create or replace function public.admin_update_channel(channel_uuid uuid,new_title text,new_description text,new_public boolean,new_username text) returns boolean language plpgsql security definer set search_path=public,private as $$ begin if not private.is_admin() then raise exception 'دسترسی ندارید'; end if; if length(trim(new_title))=0 or length(new_title)>80 then raise exception 'نام نامعتبر است'; end if; if new_username is not null and trim(new_username)<>'' and new_username !~ '^[a-z0-9_]{3,32}$' then raise exception 'شناسه نامعتبر است'; end if; if nullif(lower(trim(new_username)),'') is not null and exists(select 1 from public.channels where lower(username)=lower(trim(new_username)) and id<>channel_uuid) then raise exception 'شناسه تکراری است'; end if; update public.conversations set title=trim(new_title),description=nullif(trim(new_description),''),is_public=coalesce(new_public,false),discoverable=coalesce(new_public,false),channel_username=nullif(lower(trim(new_username)),'') where id=channel_uuid and type='group' and is_channel=true; update public.channels set title=trim(new_title),description=coalesce(nullif(trim(new_description),''),''),is_public=coalesce(new_public,false),username=nullif(lower(trim(new_username)),'') where id=channel_uuid; return found; end $$;

create or replace function public.admin_delete_channel(channel_uuid uuid) returns boolean language plpgsql security definer set search_path=public,private as $$ declare ok boolean; begin if not private.is_admin() then raise exception 'دسترسی ندارید'; end if; delete from public.channels where id=channel_uuid; ok:=found; delete from public.conversations where id=channel_uuid and is_channel=true; return ok or found; end $$;

create or replace function public.admin_regenerate_channel_invite(channel_uuid uuid) returns text language plpgsql security definer set search_path=public,private as $$ declare t text; begin if not private.is_admin() then raise exception 'دسترسی ندارید'; end if; t=encode(gen_random_bytes(18),'hex'); update public.channels set invite_token=t where id=channel_uuid; update public.conversations set invite_token=t where id=channel_uuid and is_channel=true; return t; end $$;

create or replace function public.admin_get_conversation_members(conversation_uuid uuid) returns table(user_id uuid,username text,display_name text,role text,is_banned boolean) language sql security definer set search_path=public,private as $$ select p.id,p.username,p.display_name,cm.role,p.is_banned from public.conversation_members cm join public.profiles p on p.id=cm.user_id where cm.conversation_id=conversation_uuid and cm.left_at is null and private.is_admin() order by case when cm.role='owner' then 0 else 1 end,p.username $$;
grant execute on function public.admin_get_conversation_members(uuid) to authenticated;

create or replace function public.admin_add_conversation_member(conversation_uuid uuid,user_uuid uuid) returns boolean language plpgsql security definer set search_path=public,private as $$ declare is_channel_conversation boolean; begin if not private.is_admin() then raise exception 'دسترسی ندارید'; end if; if not exists(select 1 from public.profiles where id=user_uuid) then raise exception 'کاربر پیدا نشد'; end if; select is_channel into is_channel_conversation from public.conversations where id=conversation_uuid; if not found then raise exception 'گروه یا کانال پیدا نشد'; end if; insert into public.conversation_members(conversation_id,user_id,role,left_at) values(conversation_uuid,user_uuid,'member',null) on conflict(conversation_id,user_id) do update set left_at=null,role=case when public.conversation_members.role='owner' then public.conversation_members.role else 'member' end; if coalesce(is_channel_conversation,false) then insert into public.channel_members(channel_id,user_id,role) values(conversation_uuid,user_uuid,'member') on conflict(channel_id,user_id) do update set role='member'; end if; return true; end $$;
grant execute on function public.admin_add_conversation_member(uuid,uuid) to authenticated;

create or replace function public.admin_remove_conversation_member(conversation_uuid uuid,user_uuid uuid) returns boolean language plpgsql security definer set search_path=public,private as $$ declare r text; begin if not private.is_admin() then raise exception 'دسترسی ندارید'; end if; select role into r from public.conversation_members where conversation_id=conversation_uuid and user_id=user_uuid and left_at is null; if r is null then return false; end if; if r='owner' then raise exception 'مالک را نمی‌توان حذف کرد'; end if; update public.conversation_members set left_at=now() where conversation_id=conversation_uuid and user_id=user_uuid; delete from public.channel_members where channel_id=conversation_uuid and user_id=user_uuid; return true; end $$;
grant execute on function public.admin_remove_conversation_member(uuid,uuid) to authenticated;

create or replace function public.admin_set_conversation_discoverable(conversation_uuid uuid,enabled boolean) returns boolean language plpgsql security definer set search_path=public,private as $$ begin if not private.is_admin() then raise exception 'دسترسی ندارید'; end if; update public.conversations set discoverable=enabled,is_public=case when enabled then true else is_public end where id=conversation_uuid and is_channel=true; update public.channels set is_public=case when enabled then true else is_public end where id=conversation_uuid; return found; end $$;
grant execute on function public.admin_set_conversation_discoverable(uuid,boolean) to authenticated;

create or replace function public.set_registration_enabled(enabled boolean) returns boolean language plpgsql security definer set search_path=public,private as $$ begin if not private.is_admin() then raise exception 'دسترسی ندارید'; end if; insert into public.app_settings(key,value,updated_at) values('registration_enabled',to_jsonb(enabled),now()) on conflict(key) do update set value=excluded.value,updated_at=now(); return true; end $$;
grant execute on function public.set_registration_enabled(boolean) to authenticated;
