create table if not exists public.app_settings (key text primary key, value jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
alter table public.app_settings enable row level security;
revoke all on public.app_settings from anon;
grant select on public.app_settings to authenticated;
drop policy if exists app_settings_select on public.app_settings;
create policy app_settings_select on public.app_settings for select to authenticated using (true);
insert into public.app_settings(key,value) values ('registration_enabled','false'::jsonb) on conflict (key) do nothing;

create table if not exists public.channels (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, title text not null, username text unique, description text not null default '', is_public boolean not null default true, created_at timestamptz not null default now());
create index if not exists channels_owner_idx on public.channels(owner_id);
create table if not exists public.channel_members (channel_id uuid not null references public.channels(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null default 'member' check(role in ('owner','admin','member')), joined_at timestamptz not null default now(), primary key(channel_id,user_id));
alter table public.channels enable row level security;
alter table public.channel_members enable row level security;
grant select,insert,update,delete on public.channels to authenticated;
grant select,insert,update,delete on public.channel_members to authenticated;
drop policy if exists channels_select on public.channels;
drop policy if exists channels_insert on public.channels;
drop policy if exists channels_update on public.channels;
drop policy if exists channels_delete on public.channels;
create policy channels_select on public.channels for select to authenticated using (is_public or owner_id=auth.uid() or exists(select 1 from public.channel_members cm where cm.channel_id=id and cm.user_id=auth.uid()));
create policy channels_insert on public.channels for insert to authenticated with check(owner_id=auth.uid());
create policy channels_update on public.channels for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy channels_delete on public.channels for delete to authenticated using(owner_id=auth.uid());
drop policy if exists channel_members_select on public.channel_members;
drop policy if exists channel_members_insert on public.channel_members;
drop policy if exists channel_members_update on public.channel_members;
drop policy if exists channel_members_delete on public.channel_members;
create policy channel_members_select on public.channel_members for select to authenticated using(user_id=auth.uid() or exists(select 1 from public.channels c where c.id=channel_id and c.owner_id=auth.uid()));
create policy channel_members_insert on public.channel_members for insert to authenticated with check(exists(select 1 from public.channels c where c.id=channel_id and c.owner_id=auth.uid()) or user_id=auth.uid());
create policy channel_members_update on public.channel_members for update to authenticated using(exists(select 1 from public.channels c where c.id=channel_id and c.owner_id=auth.uid()));
create policy channel_members_delete on public.channel_members for delete to authenticated using(user_id=auth.uid() or exists(select 1 from public.channels c where c.id=channel_id and c.owner_id=auth.uid()));
create or replace function public.set_registration_enabled(enabled boolean) returns boolean language plpgsql security definer set search_path=public,private as $$ begin if not private.is_admin() then raise exception 'forbidden'; end if; update public.app_settings set value=to_jsonb(enabled),updated_at=now() where key='registration_enabled'; return true; end; $$;
revoke all on function public.set_registration_enabled(boolean) from public,anon;
grant execute on function public.set_registration_enabled(boolean) to authenticated;
