BEGIN;
DROP POLICY IF EXISTS conversation_members_admin_select ON public.conversation_members;
DROP POLICY IF EXISTS conversation_members_select ON public.conversation_members;
CREATE POLICY conversation_members_select ON public.conversation_members FOR SELECT TO authenticated USING (private.is_admin() OR private.is_conversation_member(conversation_id));
DROP POLICY IF EXISTS conversations_admin_select ON public.conversations;
DROP POLICY IF EXISTS conversations_member_select ON public.conversations;
CREATE POLICY conversations_select ON public.conversations FOR SELECT TO authenticated USING (private.is_admin() OR private.is_conversation_member(id));
DROP POLICY IF EXISTS messages_admin_select ON public.messages;
DROP POLICY IF EXISTS messages_select_participants ON public.messages;
CREATE POLICY messages_select ON public.messages FOR SELECT TO authenticated USING ((SELECT auth.uid())=sender_id OR ((receiver_id IS NOT NULL) AND (SELECT auth.uid())=receiver_id) OR ((conversation_id IS NOT NULL) AND private.is_conversation_member(conversation_id)) OR private.is_admin());
DROP POLICY IF EXISTS messages_admin_delete ON public.messages;
CREATE POLICY messages_delete ON public.messages FOR DELETE TO authenticated USING (private.is_admin());
DROP POLICY IF EXISTS messages_admin_update ON public.messages;
CREATE POLICY messages_update ON public.messages FOR UPDATE TO authenticated USING (private.is_admin()) WITH CHECK (private.is_admin());
DROP POLICY IF EXISTS mentions_select_chat ON public.message_mentions;
DROP POLICY IF EXISTS message_mentions_select ON public.message_mentions;
CREATE POLICY message_mentions_select ON public.message_mentions FOR SELECT TO authenticated USING (user_id=(SELECT auth.uid()) OR EXISTS (SELECT 1 FROM public.messages m WHERE m.id=message_mentions.message_id AND (m.sender_id=(SELECT auth.uid()) OR (m.conversation_id IS NOT NULL AND private.is_conversation_member(m.conversation_id)))));
DROP POLICY IF EXISTS message_recipients_select ON public.message_recipients;
DROP POLICY IF EXISTS recipients_select_self ON public.message_recipients;
CREATE POLICY message_recipients_select ON public.message_recipients FOR SELECT TO authenticated USING (user_id=(SELECT auth.uid()) OR EXISTS (SELECT 1 FROM public.messages m WHERE m.id=message_recipients.message_id AND (m.sender_id=(SELECT auth.uid()) OR (m.conversation_id IS NOT NULL AND private.is_conversation_member(m.conversation_id)))));
DROP POLICY IF EXISTS message_recipients_update ON public.message_recipients;
DROP POLICY IF EXISTS recipients_update_self ON public.message_recipients;
CREATE POLICY message_recipients_update ON public.message_recipients FOR UPDATE TO authenticated USING (user_id=(SELECT auth.uid())) WITH CHECK (user_id=(SELECT auth.uid()));
DROP POLICY IF EXISTS support_tickets_insert ON public.support_tickets;
DROP POLICY IF EXISTS users_can_create_tickets ON public.support_tickets;
CREATE POLICY support_tickets_insert ON public.support_tickets FOR INSERT TO authenticated WITH CHECK (user_id=(SELECT auth.uid()));
DROP POLICY IF EXISTS profiles_update_display_name ON public.profiles;
CREATE POLICY profiles_update_display_name ON public.profiles FOR UPDATE TO authenticated USING (id=(SELECT auth.uid())) WITH CHECK (id=(SELECT auth.uid()));
DROP POLICY IF EXISTS messages_insert_sender_v2 ON public.messages;
DROP POLICY IF EXISTS messages_insert_sender_v3 ON public.messages;
DROP POLICY IF EXISTS messages_insert_sender_v4 ON public.messages;
CREATE POLICY messages_insert_sender_v4 ON public.messages FOR INSERT TO authenticated WITH CHECK ((SELECT auth.uid())=sender_id AND (((receiver_id IS NOT NULL) AND sender_id<>receiver_id) OR (conversation_id IS NOT NULL AND private.is_conversation_member(conversation_id) AND NOT EXISTS (SELECT 1 FROM public.conversations c WHERE c.id=messages.conversation_id AND c.is_channel AND c.created_by<>(SELECT auth.uid())))));
DROP POLICY IF EXISTS channels_insert ON public.channels;
DROP POLICY IF EXISTS channels_update ON public.channels;
DROP POLICY IF EXISTS channels_delete ON public.channels;
DROP POLICY IF EXISTS channel_members_insert ON public.channel_members;
DROP POLICY IF EXISTS channel_members_update ON public.channel_members;
DROP POLICY IF EXISTS channel_members_delete ON public.channel_members;
CREATE INDEX IF NOT EXISTS idx_chats_created_by ON public.chats(created_by);
DROP INDEX IF EXISTS mentions_user_idx;
DROP INDEX IF EXISTS message_reads_reader_idx;
DROP INDEX IF EXISTS message_reads_user_idx;
DROP INDEX IF EXISTS messages_sender_created_idx;
DROP INDEX IF EXISTS profiles_public_id_idx;
DROP INDEX IF EXISTS support_tickets_user_idx;
COMMIT;
