"use client";
import{useEffect,useState}from"react";
import{db}from"../lib/supabase-client";
import"./support-chat.css";
export default function SupportChat({onClose,embedded=false}){
 const[s,setS]=useState(null),[c,setC]=useState(null),[ms,setMs]=useState([]),[v,setV]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=async()=>{const{data,error:se}=await db.auth.getSession();if(se){setError("ارتباط با حساب برقرار نشد. دوباره تلاش کنید.");setLoading(false);return}if(!data.session){setLoading(false);return}setS(data.session);let{data:chat,error:ce}=await db.from("support_chats").select("id,status").eq("user_id",data.session.user.id).maybeSingle();if(ce){setError("گفتگوی پشتیبانی در دسترس نیست.");setLoading(false);return}if(chat){setC(chat);const{data:rows,error:me}=await db.from("support_chat_messages").select("id,sender_id,content,created_at").eq("chat_id",chat.id).order("created_at");if(me)setError("پیام‌های پشتیبانی بارگذاری نشدند.");else setMs(rows||[])}setLoading(false)};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!c)return;const ch=db.channel("support-"+c.id).on("postgres_changes",{event:"*",schema:"public",table:"support_chat_messages",filter:"chat_id=eq."+c.id},load).on("postgres_changes",{event:"*",schema:"public",table:"support_chats",filter:"id=eq."+c.id},load).subscribe();return()=>{db.removeChannel(ch)}},[c?.id]);
 const send=async()=>{const value=v.trim();if(!value||busy||!s||value.length>4000)return;setBusy(true);setError("");let cid=c?.id;if(!cid){const r=await db.rpc("get_or_create_support_chat");if(r.error){setError("گفتگوی پشتیبانی ساخته نشد. دوباره تلاش کنید.");setBusy(false);return}cid=r.data;setC({id:cid,status:"open"})}else if(c.status==="closed"){const r=await db.rpc("get_or_create_support_chat");if(r.error){setError("بازکردن گفتگوی پشتیبانی ممکن نشد.");setBusy(false);return}}
 const{error:e}=await db.from("support_chat_messages").insert({chat_id:cid,sender_id:s.user.id,content:value});if(e)setError("ارسال پیام انجام نشد. دوباره تلاش کنید.");else{setV("");await load()}setBusy(false)};
 if(loading)return <div className="usch-card">در حال بارگذاری…</div>;
 const card=<div className="usch-card" dir="rtl"><header><div className="usch-title"><span className="usch-avatar">U</span><div><b>پشتیبانی رسمی</b><small>@support · پاسخ‌گویی مستقیم</small></div></div>{onClose&&<button className="usch-close" onClick={onClose} aria-label="بستن">×</button>}</header><div className="usch-body">{error&&<div role="alert" className="usch-error">{error}</div>}{!ms.length&&<div className="usch-empty"><strong>پشتیبانی رسمی UTINOCHATV1</strong><span>سؤال یا مشکل خود را اینجا بنویسید.</span></div>}{ms.map(m=><div key={m.id} className={'usch-msg '+(m.sender_id===s?.user?.id?'mine':'theirs')}>{m.content}<time>{new Date(m.created_at).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})}</time></div>)}{c?.status==="closed"&&<div className="usch-ended">این گفتگو پایان یافته است. با ارسال پیام، گفتگوی جدید باز می‌شود.</div>}</div><div className="usch-compose"><textarea value={v} maxLength={4000} placeholder="پیامتان را بنویسید…" onChange={e=>setV(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><button onClick={send} disabled={!v.trim()||busy}>ارسال</button></div></div>;
 return embedded?card:<div className="usch-overlay">{card}</div>
}
