"use client";
import { useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";
const db=createClient("https://jcblfgrcsgbdeamogzfc.supabase.co","sb_publishable_9qBGewmR-UHx6Pc3_Gl36Q_7WhHCw2K",{auth:{persistSession:true,autoRefreshToken:true}});
export default function SupportChat({onClose}){
 const[chat,setChat]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");const{data:{user}}=await db.auth.getUser();if(!user){setLoading(false);return}let{data:c,error:e}=await db.from("support_chats").select("id,user_id,status,created_at,updated_at").eq("user_id",user.id).maybeSingle();if(e){setError(e.message);setLoading(false);return}setChat(c||null);if(c){const{data:m,error:me}=await db.from("support_chat_messages").select("id,chat_id,sender_id,content,created_at").eq("chat_id",c.id).order("created_at",{ascending:true});if(me)setError(me.message);else setMessages(m||[])}setLoading(false)}
 async function start(){if(busy)return;setBusy(true);setError("");const{data:{user}}=await db.auth.getUser();const{data:c,error:e}=await db.from("support_chats").upsert({user_id:user.id,status:"open"},{onConflict:"user_id"}).select().single();if(e)setError(e.message);else{setChat(c);setMessages([])}setBusy(false)}
 async function send(){if(!chat||chat.status!=="open"||!text.trim()||busy)return;setBusy(true);const{data:{user}}=await db.auth.getUser();const{error:e}=await db.from("support_chat_messages").insert({chat_id:chat.id,sender_id:user.id,content:text.trim()});if(e)setError(e.message);else{setText("");await load()}setBusy(false)}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!chat?.id)return;const ch=db.channel("support-chat-"+chat.id).on("postgres_changes",{event:"*",schema:"public",table:"support_chat_messages",filter:"chat_id=eq."+chat.id},()=>load()).on("postgres_changes",{event:"UPDATE",schema:"public",table:"support_chats",filter:"id=eq."+chat.id},()=>load()).subscribe();return()=>db.removeChannel(ch)},[chat?.id]);
 return <div className="support-chat-modal"><div className="support-chat-head"><div><b>پشتیبانی</b><small>ارتباط مستقیم با پشتیبانی رسمی</small></div><button onClick={onClose}>×</button></div>{loading?<div className="support-chat-empty">در حال بارگذاری…</div>:!chat?<div className="support-chat-empty"><h3>پشتیبانی</h3><p>برای شروع گفتگو با پشتیبانی، پیام خود را ارسال کنید.</p><button className="admin-button primary" onClick={start} disabled={busy}>شروع گفتگو</button></div>:<><div className="support-chat-body">{chat.status==="closed"&&<div className="support-chat-ended"><b>این گفتگو پایان یافته است.</b><span>برای شروع یک گفتگوی جدید پیام دهید.</span><button onClick={start} disabled={busy}>شروع دوباره</button></div>}{messages.map(m=><div key={m.id} className={'support-chat-msg '+(m.sender_id===chat.user_id?'mine':'staff')}><small>{m.sender_id===chat.user_id?'شما':'پشتیبانی'} · {new Date(m.created_at).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})}</small><p>{m.content}</p></div>)}</div>{chat.status==="open"&&<div className="support-chat-compose"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="پیام خود را بنویسید…" maxLength={4000}/><button onClick={send} disabled={busy||!text.trim()}>ارسال</button></div>}</>}{error&&<div className="support-chat-error">{error}</div>}</div>
}